name: "Docker Build Platform"
description: "Build a Docker image for a single platform and upload digest as artifact"
inputs:
  platform:
    description: "Target platform (e.g., linux/amd64, linux/arm64)"
    required: true
  context:
    description: "Build context path"
    required: true
  dockerfile:
    description: "Path to Dockerfile"
    required: true
  registry-image:
    description: "Registry image name (e.g., onyxdotapp/onyx-backend)"
    required: true
  ecr-cache-registry:
    description: "ECR cache registry for runs-on"
    required: true
  cache-name:
    description: "Cache name prefix (e.g., backend, web, model-server)"
    required: true
  artifact-name:
    description: "Artifact name prefix for digest upload (e.g., backend, web)"
    required: true
  build-args:
    description: "Build arguments (newline-separated KEY=VALUE pairs)"
    required: false
    default: ""
  no-cache:
    description: "Disable Docker cache"
    required: false
    default: "false"
  buildkitd-flags:
    description: "Additional buildkitd flags"
    required: false
    default: ""
  docker-username:
    description: "Docker Hub username"
    required: true
  docker-password:
    description: "Docker Hub password/token"
    required: true
  is-dry-run:
    description: "Whether this is a dry run (workflow_dispatch)"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Prepare
      id: prepare
      shell: bash
      run: |
        platform="${{ inputs.platform }}"
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
        # Extract arch suffix (amd64 or arm64)
        echo "ARCH_SUFFIX=${platform#linux/}" >> $GITHUB_ENV

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # ratchet:docker/metadata-action@v5
      with:
        images: ${{ inputs.is-dry-run == 'true' && inputs.ecr-cache-registry || inputs.registry-image }}
        flavor: |
          latest=false

    - name: Set up QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # ratchet:docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # ratchet:docker/setup-buildx-action@v3
      with:
        buildkitd-flags: ${{ inputs.buildkitd-flags }}

    - name: Login to Docker Hub
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # ratchet:docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build and push
      id: build
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # ratchet:docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platform }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ inputs.is-dry-run == 'true' && inputs.ecr-cache-registry || inputs.registry-image }}
        build-args: ${{ inputs.build-args }}
        cache-from: |
          type=registry,ref=${{ inputs.registry-image }}:latest
          type=registry,ref=${{ inputs.ecr-cache-registry }}:${{ inputs.cache-name }}-cache-${{ env.ARCH_SUFFIX }}
        cache-to: type=registry,ref=${{ inputs.ecr-cache-registry }}:${{ inputs.cache-name }}-cache-${{ env.ARCH_SUFFIX }},mode=max
        outputs: type=image,push-by-digest=true,name-canonical=true,push=true
        no-cache: ${{ inputs.no-cache == 'true' }}

    - name: Export digest
      shell: bash
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"

    - name: Upload digest
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # ratchet:actions/upload-artifact@v4
      with:
        name: digests-${{ inputs.artifact-name }}-${{ env.PLATFORM_PAIR }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1

