#!/bin/bash
set -e

# Onyx DigitalOcean Deployment Script
# Deploys Onyx to a DigitalOcean Ubuntu 24.04 droplet

DOMAIN="klugermax.com"
DROPLET_IP="45.55.68.178"
SSL_EMAIL="robimoller@gmail.com"
REPO_URL="https://github.com/HOP-RAG/HOP.git"
DEPLOY_DIR="/opt/onyx"

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running on Ubuntu
if ! grep -q "Ubuntu" /etc/os-release; then
    log_error "This script is designed for Ubuntu. Exiting."
    exit 1
fi

log_info "Starting Onyx deployment to DigitalOcean..."
log_info "Domain: $DOMAIN"
log_info "IP: $DROPLET_IP"

# Phase 1: Install Docker and dependencies
log_info "Phase 1: Installing Docker and Docker Compose..."
sudo apt-get update
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    git

# Add Docker GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

# Add Docker repository
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install Docker
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker compose-plugin

# Enable Docker daemon
sudo systemctl enable docker
sudo systemctl start docker

# Add current user to docker group
sudo usermod -aG docker $(whoami)
log_info "Docker installed successfully"

# Phase 2: Clone repository
log_info "Phase 2: Cloning Onyx repository..."
sudo mkdir -p $DEPLOY_DIR
sudo chown $(whoami):$(whoami) $DEPLOY_DIR

cd $DEPLOY_DIR || exit 1

if [ ! -d ".git" ]; then
    git clone --branch main $REPO_URL .
    log_info "Repository cloned"
else
    log_info "Repository already cloned, pulling latest..."
    git pull origin main
fi

# Phase 3: Create data directories
log_info "Phase 3: Creating persistent volume directories..."
mkdir -p postgres_data redis_data vespa_data minio_data nginx_logs

# Phase 4: Create environment configuration
log_info "Phase 4: Creating environment configuration..."

cat > .env << 'EOF'
# Onyx DigitalOcean Sandbox Deployment
# Generated by deploy-digitalocean.sh

# Service Configuration
IMAGE_TAG=latest
DOMAIN_NAME=klugermax.com
DATABASE_URL=postgresql://postgres:password@relational_db:5432/onyx
REDIS_URL=redis://redis:6379

# PostgreSQL
POSTGRES_USER=postgres
POSTGRES_PASSWORD=password
POSTGRES_DB=onyx

# MinIO S3 Configuration
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin
MINIO_DOMAIN=klugermax.com
AWS_ACCESS_KEY_ID=minioadmin
AWS_SECRET_ACCESS_KEY=minioadmin
AWS_REGION=us-east-1
S3_ENDPOINT_URL=http://minio:9000
FILE_STORE_BACKEND=s3

# Model Server
MODEL_SERVER_HOST=inference_model_server
MODEL_SERVER_PORT=9000
EMBEDDING_MODEL=nomic-embed-text-v1.5

# Vespa Vector Database
VESPA_HOST=vespa
VESPA_PORT=8081

# Celery & Background Jobs
USE_LIGHTWEIGHT_BACKGROUND_WORKER=true
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/1

# Security
SECRET_KEY=$(openssl rand -hex 32)
AUTH_TYPE=basic
DISABLE_AUTH=false

# Features
DISABLE_VECTOR_DB=false
DISABLE_LLM_CHUNK_FILTER=true

# SSL/TLS - Let's Encrypt
LETSENCRYPT_EMAIL=robimoller@gmail.com

# Logging
LOG_LEVEL=INFO

# Optional: LLM Configuration
# Uncomment and configure if using LLM features
# LLM_PROVIDER=openai
# OPENAI_API_KEY=your-key-here

# Optional: OAuth (disabled for sandbox)
# OAUTH_ENABLED=false
EOF

log_info "Environment configuration created at .env"

# Phase 5: Update docker compose for production
log_info "Phase 5: Setting up docker compose configuration..."

# Copy prod compose file as base if available
if [ -f "deployment/docker_compose/docker compose.prod.yml" ]; then
    log_info "Using production docker compose configuration"
    cp deployment/docker_compose/docker compose.prod.yml docker compose.yml
elif [ -f "deployment/docker_compose/docker compose.yml" ]; then
    log_info "Using standard docker compose configuration"
    cp deployment/docker_compose/docker compose.yml docker compose.yml
else
    log_error "Could not find docker compose files in deployment/docker_compose/"
    exit 1
fi

# Phase 6: Pull images
log_info "Phase 6: Pulling Docker images (this may take a few minutes)..."
sudo docker compose pull

# Phase 7: Start services
log_info "Phase 7: Starting Onyx services..."
sudo docker compose up -d

log_info "Waiting for services to initialize..."
sleep 10

# Phase 8: Check service health
log_info "Phase 8: Verifying service health..."
attempt=0
max_attempts=30

while [ $attempt -lt $max_attempts ]; do
    if sudo docker compose ps | grep -q "healthy\|running"; then
        log_info "Services are running"
        break
    fi
    log_info "Waiting for services... ($((attempt + 1))/$max_attempts)"
    sleep 2
    attempt=$((attempt + 1))
done

# Phase 9: Run database migrations
log_info "Phase 9: Running database migrations..."
sudo docker compose exec -T backend alembic upgrade head

log_info ""
log_info "==================================================="
log_info "✓ Onyx deployment complete!"
log_info "==================================================="
log_info ""
log_info "Next steps:"
log_info "1. Verify DNS: Visit your domain DNS settings and confirm A record points to $DROPLET_IP"
log_info "2. Wait for DNS propagation (5-15 minutes typically)"
log_info "3. Access your instance:"
log_info "   - HTTP:  http://$DOMAIN"
log_info "   - HTTPS: https://$DOMAIN (after DNS propagates)"
log_info ""
log_info "To check service logs:"
log_info "   cd $DEPLOY_DIR && sudo docker compose logs -f"
log_info ""
log_info "To check specific service:"
log_info "   cd $DEPLOY_DIR && sudo docker compose logs -f backend"
log_info ""
log_info "To stop services:"
log_info "   cd $DEPLOY_DIR && sudo docker compose down"
log_info ""
log_info "==================================================="
