#!/bin/bash
set -e

# Onyx DigitalOcean Deployment Script
# Deploys Onyx to a DigitalOcean Ubuntu 24.04 droplet

DOMAIN="klugermax.com"
DROPLET_IP="45.55.68.178"
SSL_EMAIL="robimoller@gmail.com"
REPO_URL="https://github.com/HOP-RAG/HOP.git"
DEPLOY_DIR="/opt/onyx"

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running on Ubuntu
if ! grep -q "Ubuntu" /etc/os-release; then
    log_error "This script is designed for Ubuntu. Exiting."
    exit 1
fi

log_info "Starting Onyx deployment to DigitalOcean..."
log_info "Domain: $DOMAIN"
log_info "IP: $DROPLET_IP"

# Phase 1: Install Docker and dependencies
log_info "Phase 1: Checking Docker installation..."

if command -v docker &> /dev/null; then
    log_info "Docker is already installed, skipping installation"
else
    log_info "Installing Docker and Docker Compose..."
    sudo apt-get update
    sudo apt-get install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg \
        lsb-release \
        git

    # Add Docker GPG key
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    # Add Docker repository
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    # Install Docker
    sudo apt-get update
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

    # Enable Docker daemon
    sudo systemctl enable docker
    sudo systemctl start docker
fi

# Ensure docker group membership
sudo usermod -aG docker $(whoami) 2>/dev/null || true
log_info "Docker ready"

# Phase 2: Clone repository
log_info "Phase 2: Cloning Onyx repository..."
sudo mkdir -p $DEPLOY_DIR
sudo chown $(whoami):$(whoami) $DEPLOY_DIR

cd $DEPLOY_DIR || exit 1

if [ ! -d ".git" ]; then
    git clone --branch develop $REPO_URL .
    log_info "Repository cloned"
else
    log_info "Repository already cloned, pulling latest..."
    git fetch origin develop
    git reset --hard origin/develop
fi

# Phase 3: Create data directories
log_info "Phase 3: Creating persistent volume directories..."
mkdir -p postgres_data redis_data vespa_data minio_data nginx_logs

# Phase 4: Create environment configuration
log_info "Phase 4: Creating environment configuration..."

cat > .env << 'EOF'
# Onyx DigitalOcean Sandbox Deployment
# Generated by deploy-digitalocean.sh

# Service Configuration
IMAGE_TAG=latest
DOMAIN_NAME=klugermax.com
DATABASE_URL=postgresql://postgres:password@relational_db:5432/onyx
REDIS_URL=redis://redis:6379

# PostgreSQL
POSTGRES_USER=postgres
POSTGRES_PASSWORD=password
POSTGRES_DB=onyx

# MinIO S3 Configuration
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin
MINIO_DOMAIN=klugermax.com
AWS_ACCESS_KEY_ID=minioadmin
AWS_SECRET_ACCESS_KEY=minioadmin
AWS_REGION=us-east-1
S3_ENDPOINT_URL=http://minio:9000
FILE_STORE_BACKEND=s3

# Model Server
MODEL_SERVER_HOST=inference_model_server
MODEL_SERVER_PORT=9000
EMBEDDING_MODEL=nomic-embed-text-v1.5

# Vespa Vector Database
VESPA_HOST=vespa
VESPA_PORT=8081

# Celery & Background Jobs
USE_LIGHTWEIGHT_BACKGROUND_WORKER=true
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/1

# Security
SECRET_KEY=$(openssl rand -hex 32)
AUTH_TYPE=basic
DISABLE_AUTH=false

# Features
DISABLE_VECTOR_DB=false
DISABLE_LLM_CHUNK_FILTER=true

# SSL/TLS - Let's Encrypt
LETSENCRYPT_EMAIL=robimoller@gmail.com

# Logging
LOG_LEVEL=INFO

# Optional: LLM Configuration
# Uncomment and configure if using LLM features
# LLM_PROVIDER=openai
# OPENAI_API_KEY=your-key-here

# Optional: OAuth (disabled for sandbox)
# OAUTH_ENABLED=false
EOF

log_info "Environment configuration created at .env"

# Create nginx environment file
cat > .env.nginx << 'EOF'
DOMAIN=klugermax.com
EMAIL=robimoller@gmail.com
SSL_CERT_FILE_NAME=ssl.cert
SSL_CERT_KEY_FILE_NAME=ssl.key
EOF

log_info "Nginx environment configuration created at .env.nginx"

# Phase 5: Update docker compose for production
log_info "Phase 5: Setting up docker compose configuration..."

# Copy prod compose file as base if available
if [ -f "deployment/docker_compose/docker-compose.prod.yml" ]; then
    log_info "Using production docker-compose configuration"
    cp deployment/docker_compose/docker-compose.prod.yml docker-compose.yml
elif [ -f "deployment/docker_compose/docker-compose.yml" ]; then
    log_info "Using standard docker-compose configuration"
    cp deployment/docker_compose/docker-compose.yml docker-compose.yml
else
    log_error "Could not find docker-compose files in deployment/docker_compose/"
    exit 1
fi

# Add port mappings for api_server and web_server for direct access
log_info "Configuring service port mappings..."

# Add ports to api_server (port 8080)
if ! grep -q "api_server:" docker-compose.yml | grep -A 50 "ports:"; then
    sed -i '/api_server:/,/environment:/ {
      /restart: unless-stopped/a\    ports:\n      - "8080:8080"
    }' docker-compose.yml
    log_info "Added port mapping for api_server (8080)"
fi

# Add ports to web_server (port 3000)
if ! grep -q "web_server:" docker-compose.yml | grep -A 50 "ports:"; then
    sed -i '/web_server:/,/environment:/ {
      /restart: unless-stopped/a\    ports:\n      - "3000:3000"
    }' docker-compose.yml
    log_info "Added port mapping for web_server (3000)"
fi

# Phase 6: Pull images
log_info "Phase 6: Pulling Docker images (this may take a few minutes)..."
sudo docker compose pull

# Phase 7: Start services
log_info "Phase 7: Starting Onyx services..."
sudo docker compose up -d

log_info "Waiting for services to initialize..."
sleep 10

# Phase 8: Check service health
log_info "Phase 8: Verifying service health..."
attempt=0
max_attempts=30

while [ $attempt -lt $max_attempts ]; do
    if sudo docker compose ps | grep -q "healthy\|running"; then
        log_info "Services are running"
        break
    fi
    log_info "Waiting for services... ($((attempt + 1))/$max_attempts)"
    sleep 2
    attempt=$((attempt + 1))
done

# Phase 9: Run database migrations
log_info "Phase 9: Running database migrations..."
sudo docker compose exec -T backend alembic upgrade head

# Phase 10: Set up Nginx reverse proxy
log_info "Phase 10: Setting up Nginx reverse proxy..."

cat > nginx-simple.conf << 'NGINXEOF'
events {
    worker_connections 1024;
}

http {
    upstream api {
        server api_server:8080;
    }

    upstream web {
        server web_server:3000;
    }

    # Redirect HTTP to HTTPS
    server {
        listen 80;
        server_name $DOMAIN www.$DOMAIN;

        # Allow Let's Encrypt validation
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Redirect everything else to HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    # HTTPS server
    server {
        listen 443 ssl;
        server_name $DOMAIN www.$DOMAIN;
        client_max_body_size 100M;

        # SSL certificates
        ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # API routes - strip /api prefix
        location /api/ {
            proxy_pass http://api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

        # Web frontend
        location / {
            proxy_pass http://web;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
NGINXEOF

log_info "Nginx configuration created"

# Phase 11: Get SSL certificate from Let's Encrypt
log_info "Phase 11: Getting SSL certificate from Let's Encrypt..."

sudo docker run --rm \
  -v /etc/letsencrypt:/etc/letsencrypt \
  -p 80:80 \
  -p 443:443 \
  certbot/certbot certonly \
  --standalone \
  -d $DOMAIN \
  -d www.$DOMAIN \
  --non-interactive \
  --agree-tos \
  --email $SSL_EMAIL

if [ -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]; then
    log_info "SSL certificate obtained successfully"
else
    log_warn "SSL certificate generation failed - HTTPS may not work"
fi

# Phase 12: Start Nginx reverse proxy
log_info "Phase 12: Starting Nginx reverse proxy..."

# Stop old nginx proxy if it exists
sudo docker stop onyx-proxy 2>/dev/null || true
sudo docker rm onyx-proxy 2>/dev/null || true

sudo docker run -d \
  --name onyx-proxy \
  --network onyx_default \
  -p 80:80 \
  -p 443:443 \
  -v $(pwd)/nginx-simple.conf:/etc/nginx/nginx.conf:ro \
  -v /etc/letsencrypt:/etc/letsencrypt:ro \
  -v /var/www/certbot:/var/www/certbot \
  nginx:alpine

log_info "Nginx proxy started on ports 80 and 443"

log_info ""
log_info "==================================================="
log_info "✓ Onyx deployment complete!"
log_info "==================================================="
log_info ""
log_info "✓ Deployment successful!"
log_info ""
log_info "Access your instance:"
log_info "   HTTPS: https://$DOMAIN (secure with Let's Encrypt SSL)"
log_info "   HTTP:  http://$DOMAIN (auto-redirects to HTTPS)"
log_info ""
log_info "Useful commands:"
log_info "   # View all logs: cd $DEPLOY_DIR && sudo docker compose logs -f"
log_info "   # View backend: cd $DEPLOY_DIR && sudo docker compose logs -f api_server"
log_info "   # Service status: cd $DEPLOY_DIR && sudo docker compose ps"
log_info "   # Stop services: cd $DEPLOY_DIR && sudo docker compose down"
log_info ""
log_info "==================================================="
