[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "onyx"
version = "0.0.0"

[tool.setuptools.packages.find]
where = ["backend"]
include = ["onyx*", "tests*"]