"use client";

import React, { useEffect, useRef, useState } from "react";
import { format, startOfDay, subDays } from "date-fns";
import useSWR from "swr";
import {
  Button,
  Calendar,
  LineItemButton,
  MessageCard,
  Pagination,
  Popover,
  Text,
} from "@opal/components";
import { ContentAction, PageLoader, toast } from "@opal/layouts";
import {
  SvgCalendar,
  SvgDownload,
  SvgDownloadCloud,
  SvgSimpleLoader,
  SvgSpreadsheetFile,
  SvgX,
} from "@opal/icons";
import { humanReadableFormat, humanReadableFormatWithTime } from "@opal/time";
import { errorHandlingFetcher } from "@/lib/fetcher";
import { SWR_KEYS } from "@/lib/swr-keys";
import { UsageReport } from "./types";

interface ReportPeriod {
  label: string;
  range?: { from: Date; to: Date };
}

const PRESET_DAYS: { label: string; days: number }[] = [
  { label: "Today", days: 1 },
  { label: "Last 7 days", days: 7 },
  { label: "Last 30 days", days: 30 },
  { label: "Last 3 months", days: 90 },
];

function presetPeriod(label: string, days: number): ReportPeriod {
  const to = startOfDay(new Date());
  return { label, range: { from: subDays(to, days - 1), to } };
}

const PAGE_SIZE = 8;
const POLL_INTERVAL_MS = 3_000;
const SLOW_REPORT_AFTER_MS = 20_000;
const REPORT_TIMEOUT_MS = 5 * 60_000;

function periodLabel(report: UsageReport): string {
  return report.period_from
    ? `${humanReadableFormat(report.period_from)} – ${humanReadableFormat(
        report.period_to!
      )}`
    : "All time";
}

interface PendingReportRowProps {
  rangeLabel: string;
  slow: boolean;
}

function PendingReportRow({ rangeLabel, slow }: PendingReportRowProps) {
  return (
    <div
      className="rounded-12 border border-border-01 bg-background-tint-01 motion-safe:animate-pulse"
      data-testid="pending-report-row"
    >
      <ContentAction
        sizePreset="main-ui"
        variant="section"
        icon={SvgSpreadsheetFile}
        title="Preparing report…"
        description={
          slow
            ? "Still working. You can leave this page; the report will appear here."
            : `${rangeLabel} · usually ready in under a minute`
        }
        padding="md"
        center
        rightChildren={
          <SvgSimpleLoader
            size={16}
            className="shrink-0 animate-spin stroke-text-03 motion-reduce:animate-none"
          />
        }
      />
    </div>
  );
}

interface ReportRowProps {
  report: UsageReport;
  justArrived: boolean;
}

function ReportRow({ report, justArrived }: ReportRowProps) {
  return (
    <div
      className={
        justArrived
          ? "rounded-12 border border-border-01 bg-background-neutral-00 motion-safe:animate-in motion-safe:fade-in motion-safe:slide-in-from-top-2 motion-safe:duration-500"
          : "rounded-12 border border-border-01 bg-background-neutral-00"
      }
    >
      <ContentAction
        sizePreset="main-ui"
        variant="section"
        icon={SvgSpreadsheetFile}
        title={periodLabel(report)}
        description={`Generated by ${report.requestor ?? "system"} · ${humanReadableFormatWithTime(report.time_created)}`}
        padding="md"
        center
        rightChildren={
          <Button
            prominence="tertiary"
            icon={SvgDownload}
            tooltip="Download CSV"
            aria-label={`Download report for ${periodLabel(report)}`}
            href={`/api/admin/usage-report/${report.report_name}`}
          />
        }
      />
    </div>
  );
}

interface GenerateReportMenuProps {
  disabled: boolean;
  pending: boolean;
  onGenerate: (period: ReportPeriod) => void;
}

function GenerateReportMenu({
  disabled,
  pending,
  onGenerate,
}: GenerateReportMenuProps) {
  const [open, setOpen] = useState(false);
  const [view, setView] = useState<"presets" | "calendar">("presets");
  const [pendingStart, setPendingStart] = useState<Date | undefined>(undefined);
  const [draftRange, setDraftRange] = useState<
    { from: Date; to?: Date } | undefined
  >(undefined);

  function reset() {
    setView("presets");
    setPendingStart(undefined);
    setDraftRange(undefined);
  }

  return (
    <Popover
      open={open}
      onOpenChange={(nextOpen) => {
        setOpen(nextOpen);
        if (!nextOpen) reset();
      }}
    >
      <Popover.Trigger asChild>
        <Button icon={SvgDownloadCloud} disabled={disabled}>
          {pending ? "Generating…" : "Generate report"}
        </Button>
      </Popover.Trigger>
      <Popover.Content
        align="end"
        side="bottom"
        width={view === "presets" ? "lg" : "fit"}
      >
        {view === "presets" ? (
          <Popover.Menu>
            {[
              ...PRESET_DAYS.map((preset) => (
                <Popover.Close asChild key={preset.label}>
                  <LineItemButton
                    title={preset.label}
                    onClick={() =>
                      onGenerate(presetPeriod(preset.label, preset.days))
                    }
                    rounding="md"
                    selectVariant="select-heavy"
                    sizePreset="main-ui"
                    state="empty"
                    variant="section"
                    width="full"
                  />
                </Popover.Close>
              )),
              <Popover.Close asChild key="all-time">
                <LineItemButton
                  title="All time"
                  onClick={() => onGenerate({ label: "All time" })}
                  rounding="md"
                  selectVariant="select-heavy"
                  sizePreset="main-ui"
                  state="empty"
                  variant="section"
                  width="full"
                />
              </Popover.Close>,
              null,
              <LineItemButton
                key="custom"
                icon={SvgCalendar}
                title="Custom period…"
                onClick={() => setView("calendar")}
                rounding="md"
                selectVariant="select-heavy"
                sizePreset="main-ui"
                state="empty"
                variant="section"
                width="full"
              />,
            ]}
          </Popover.Menu>
        ) : (
          <div className="flex flex-col gap-1 p-2">
            <Text font="secondary-body" color="text-03">
              {pendingStart
                ? "Pick the end of the period"
                : "Pick the start of the period"}
            </Text>
            <Calendar
              mode="range"
              selected={draftRange}
              onDayClick={(day) => {
                if (!pendingStart) {
                  setDraftRange({ from: day });
                  setPendingStart(day);
                  return;
                }
                const from = day < pendingStart ? day : pendingStart;
                const to = day < pendingStart ? pendingStart : day;
                onGenerate({
                  label: `${format(from, "MMM d, y")} – ${format(to, "MMM d, y")}`,
                  range: { from, to },
                });
                setOpen(false);
                reset();
              }}
              numberOfMonths={1}
              disabled={(date) => date > new Date()}
            />
          </div>
        )}
      </Popover.Content>
    </Popover>
  );
}

export default function UsageReports() {
  const [page, setPage] = useState(1);
  const [requesting, setRequesting] = useState(false);
  const [pendingSince, setPendingSince] = useState<number | null>(null);
  const [pendingLabel, setPendingLabel] = useState<string>("");
  const [pendingSlow, setPendingSlow] = useState(false);
  const [arrivedReportName, setArrivedReportName] = useState<string | null>(
    null
  );
  const [pendingReportId, setPendingReportId] = useState<string | null>(null);
  const slowTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const reportTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const pending = pendingSince !== null;
  const {
    data: reports,
    error: listError,
    isLoading: listLoading,
    mutate,
  } = useSWR<UsageReport[]>(SWR_KEYS.usageReport, errorHandlingFetcher, {
    refreshInterval: pending ? POLL_INTERVAL_MS : 0,
  });

  useEffect(() => {
    if (listError) console.error("Failed to load usage reports:", listError);
  }, [listError]);

  useEffect(() => {
    if (!reports || !pendingReportId) return;
    const completed = reports.find((report) =>
      report.report_name.includes(pendingReportId)
    );
    if (completed && pending) {
      setPendingSince(null);
      setPendingReportId(null);
      setPendingSlow(false);
      setArrivedReportName(completed.report_name);
      setPage(1);
      toast.success("Usage report ready.");
      if (slowTimerRef.current) {
        clearTimeout(slowTimerRef.current);
        slowTimerRef.current = null;
      }
      if (reportTimeoutRef.current) {
        clearTimeout(reportTimeoutRef.current);
        reportTimeoutRef.current = null;
      }
    }
  }, [reports, pending, pendingReportId]);

  useEffect(() => {
    return () => {
      if (slowTimerRef.current) clearTimeout(slowTimerRef.current);
      if (reportTimeoutRef.current) clearTimeout(reportTimeoutRef.current);
    };
  }, []);

  async function requestReport(period: ReportPeriod): Promise<void> {
    setRequesting(true);
    try {
      const reportId = crypto.randomUUID();
      const res = await fetch("/api/admin/usage-report", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          period_from: period.range ? period.range.from.toISOString() : null,
          period_to: period.range ? period.range.to.toISOString() : null,
          report_id: reportId,
        }),
      });
      if (!res.ok) {
        throw Error(`Received an error: ${res.statusText}`);
      }
      setPendingSince(Date.now());
      setPendingReportId(reportId);
      setPendingLabel(period.label);
      setPendingSlow(false);
      setArrivedReportName(null);
      slowTimerRef.current = setTimeout(
        () => setPendingSlow(true),
        SLOW_REPORT_AFTER_MS
      );
      reportTimeoutRef.current = setTimeout(() => {
        setPendingSince(null);
        setPendingReportId(null);
        setPendingSlow(false);
        toast.error(
          "Report generation is taking too long. Try again or check back later."
        );
        reportTimeoutRef.current = null;
      }, REPORT_TIMEOUT_MS);
      await mutate();
    } catch (error) {
      console.error("Failed to start usage report generation:", error);
      const message = error instanceof Error ? error.message : "unknown error";
      toast.error(`Failed to start report generation: ${message}`);
    } finally {
      setRequesting(false);
    }
  }

  const orderedReports = reports ? [...reports].reverse() : [];
  const totalPages = Math.max(1, Math.ceil(orderedReports.length / PAGE_SIZE));
  const pageReports = orderedReports.slice(
    PAGE_SIZE * (page - 1),
    PAGE_SIZE * page
  );

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex flex-col gap-0.5">
          <Text font="heading-h3">Usage reports</Text>
          <Text font="secondary-body" color="text-03">
            Export per-user usage as a CSV. Reports build in the background and
            stay available here.
          </Text>
        </div>
        <GenerateReportMenu
          disabled={requesting || pending || listLoading}
          pending={pending}
          onGenerate={(period) => void requestReport(period)}
        />
      </div>

      {listLoading ? (
        <PageLoader />
      ) : listError ? (
        <MessageCard
          variant="error"
          icon={SvgX}
          title="Failed to load usage reports."
        />
      ) : (
        <div className="flex flex-col gap-2">
          {pending && page === 1 && (
            <PendingReportRow rangeLabel={pendingLabel} slow={pendingSlow} />
          )}
          {orderedReports.length === 0 && !pending ? (
            <div className="rounded-12 border border-dashed border-border-02 p-4">
              <Text font="secondary-body" color="text-03" as="p">
                No reports yet. Pick a period and generate your first one.
              </Text>
            </div>
          ) : (
            pageReports.map((report) => (
              <ReportRow
                key={report.report_name}
                report={report}
                justArrived={report.report_name === arrivedReportName}
              />
            ))
          )}
          {totalPages > 1 && (
            <div className="flex justify-end pt-1">
              <Pagination
                variant="simple"
                currentPage={page}
                totalPages={totalPages}
                onChange={setPage}
              />
            </div>
          )}
        </div>
      )}
    </div>
  );
}
