GENERAL_SEP_PAT = "--------------"  # Same length as Langchain's separator
CODE_BLOCK_PAT = "```\n{}\n```"
TRIPLE_BACKTICK = "```"
QUESTION_PAT = "Запрос:"
FINAL_QUERY_PAT = "Окончаельный запрос:"
THOUGHT_PAT = "Мысль:"
ANSWER_PAT = "Ответ:"
ANSWERABLE_PAT = "Отвечающий:"
FINAL_ANSWER_PAT = "Окончательный ответ:"
QUOTE_PAT = "Цитата:"
QUOTES_PAT_PLURAL = "Цитаты:"
INVALID_PAT = "Недействительный:"
SOURCES_KEY = "источники"

DEFAULT_IGNORE_STATEMENT = " Игнорируй любые контекстные документы, которые не имеют отношения к делу."
