package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// generatedRuleMarker identifies rule files this command wrote, so a rerun can
// replace them without touching rules the developer added by hand.
const generatedRuleMarker = "<!-- Generated by `ods install-skill`. Do not edit; changes belong in onyx-llm-context. -->"

// installCursorSkills renders every skill as a Cursor rule under
// .cursor/rules/ at the repo root. Enforced skills become alwaysApply rules;
// on-demand skills become agent-requested rules that Cursor attaches when
// their description matches, or on an explicit @name mention.
//
// .cursor/* is gitignored in the Onyx repo, so the private content never
// reaches a public diff. Files are real copies rather than symlinks because
// Cursor does not reliably follow symlinked rule files.
func installCursorSkills(
	cmd *cobra.Command, skills []llmContextSkill, repoRoot string,
) error {
	if len(skills) == 0 {
		return nil
	}
	rulesDir := filepath.Join(repoRoot, ".cursor", "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		return fmt.Errorf("could not create %s: %w", rulesDir, err)
	}

	if err := removeStaleGeneratedRules(cmd, rulesDir, skills); err != nil {
		return err
	}

	for _, skill := range skills {
		dest := filepath.Join(rulesDir, skill.Name+".mdc")
		content := renderCursorRule(skill)
		existing, err := os.ReadFile(dest)
		if err == nil && string(existing) == content {
			_, _ = fmt.Fprintf(cmd.OutOrStdout(), "Up to date %s\n", dest)
			continue
		}
		if err := os.WriteFile(dest, []byte(content), 0o644); err != nil {
			return fmt.Errorf("could not write %s: %w", dest, err)
		}
		_, _ = fmt.Fprintf(cmd.OutOrStdout(), "Installed %s\n", dest)
	}
	return nil
}

func renderCursorRule(skill llmContextSkill) string {
	return fmt.Sprintf(
		"---\ndescription: %s\nalwaysApply: %t\n---\n\n%s\n\n%s",
		skill.Description,
		skill.Enforced,
		generatedRuleMarker,
		skill.Body,
	)
}

// removeStaleGeneratedRules deletes previously generated rule files whose
// skill no longer exists, identified by the marker so hand-written rules
// survive whatever they are named.
func removeStaleGeneratedRules(
	cmd *cobra.Command, rulesDir string, skills []llmContextSkill,
) error {
	current := make(map[string]bool, len(skills))
	for _, skill := range skills {
		current[skill.Name+".mdc"] = true
	}

	entries, err := os.ReadDir(rulesDir)
	if err != nil {
		return fmt.Errorf("could not read %s: %w", rulesDir, err)
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".mdc") {
			continue
		}
		if current[entry.Name()] {
			continue
		}
		path := filepath.Join(rulesDir, entry.Name())
		content, err := os.ReadFile(path)
		if err != nil || !strings.Contains(string(content), generatedRuleMarker) {
			continue
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("could not remove stale rule %s: %w", path, err)
		}
		_, _ = fmt.Fprintf(cmd.OutOrStdout(), "Removed %s\n", path)
	}
	return nil
}
