/**
 * generate-theme.ts — Opal CSS -> mobile theme bridge.
 *
 * Parses Onyx's "Opal" design tokens (colors.css, typography.css, root.css) and
 * emits flattened, concrete-valued theme objects + a NativeWind preset that the
 * mobile app consumes. NativeWind cannot resolve `var(--x)` indirection at the
 * value level, so every color is recursively flattened to a concrete hex.
 *
 * Run with bun: `bun scripts/generate-theme.ts`
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const MOBILE_ROOT = join(__dirname, "..");
const OPAL_STYLES = join(
  MOBILE_ROOT,
  "..",
  "web",
  "lib",
  "opal",
  "src",
  "styles",
);
const OPAL_ROOT_CSS = join(MOBILE_ROOT, "..", "web", "lib", "opal", "src", "root.css");
const OUT_DIR = join(MOBILE_ROOT, "src", "theme", "generated");

const HEADER =
  "// AUTO-GENERATED by mobile/scripts/generate-theme.ts from Opal CSS. Do not edit by hand.\n";

// ---------------------------------------------------------------------------
// CSS parsing helpers
// ---------------------------------------------------------------------------

type Decls = Record<string, string>;

/**
 * Strip /* ... *\/ comments so they don't confuse the brace/declaration scanner.
 */
function stripComments(css: string): string {
  return css.replace(/\/\*[\s\S]*?\*\//g, "");
}

/**
 * Pull every `--name: value;` declaration out of a chunk of CSS text.
 * Later declarations override earlier ones (CSS cascade within a layer).
 */
function parseDeclarations(block: string): Decls {
  const decls: Decls = {};
  const re = /(--[a-z0-9-]+)\s*:\s*([^;]+);/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(block)) !== null) {
    const name = m[1]!.trim();
    const value = m[2]!.trim();
    decls[name] = value;
  }
  return decls;
}

/**
 * Extract the body of the FIRST selector block matching `selector` (e.g. ".dark").
 * Handles nested braces (none expected here, but safe). Returns "" if not found.
 */
function extractBlockBody(css: string, selector: string): string {
  const idx = css.indexOf(selector);
  if (idx === -1) return "";
  const braceStart = css.indexOf("{", idx);
  if (braceStart === -1) return "";
  let depth = 0;
  for (let i = braceStart; i < css.length; i++) {
    const ch = css[i];
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) return css.slice(braceStart + 1, i);
    }
  }
  return "";
}

/**
 * Collect declarations from ALL `:root { ... }` blocks, in document order so
 * later blocks override earlier ones (matches CSS cascade for equal specificity).
 */
function parseAllRootBlocks(css: string): Decls {
  const decls: Decls = {};
  const re = /:root\s*\{/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(css)) !== null) {
    const braceStart = m.index + m[0].length - 1;
    let depth = 0;
    let end = -1;
    for (let i = braceStart; i < css.length; i++) {
      const ch = css[i];
      if (ch === "{") depth++;
      else if (ch === "}") {
        depth--;
        if (depth === 0) {
          end = i;
          break;
        }
      }
    }
    if (end === -1) break;
    const body = css.slice(braceStart + 1, end);
    Object.assign(decls, parseDeclarations(body));
  }
  return decls;
}

// ---------------------------------------------------------------------------
// var() resolution -> concrete values
// ---------------------------------------------------------------------------

/**
 * Recursively resolve a token value to a concrete (non-var) value using the
 * provided declaration map. Handles multi-level chains like
 * background-tint-01 -> tint-02 -> stone-02 -> #fafafa.
 */
function resolveValue(
  rawValue: string,
  decls: Decls,
  seen: Set<string> = new Set(),
): string {
  const value = rawValue.trim();
  const varMatch = value.match(/^var\(\s*(--[a-z0-9-]+)\s*\)$/i);
  if (!varMatch) {
    // Not a pure var() reference -> already concrete (hex, keyword, etc.).
    return value;
  }
  const refName = varMatch[1]!;
  if (seen.has(refName)) {
    throw new Error(`Cyclic var reference detected at ${refName}`);
  }
  const refValue = decls[refName];
  if (refValue === undefined) {
    throw new Error(`Unresolved var reference: ${refName}`);
  }
  seen.add(refName);
  return resolveValue(refValue, decls, seen);
}

// ---------------------------------------------------------------------------
// Semantic-token classification
// ---------------------------------------------------------------------------

// Raw base-palette prefixes that must NOT appear as semantic theme keys.
const BASE_PREFIXES = [
  "grey-",
  "alpha-grey-",
  "blue-",
  "green-",
  "red-",
  "orange-",
  "purple-",
  "neon-",
  "stone-",
  "chalk-",
  "slate-",
  "tint-",
  "onyx-",
  "font-",
];

// Semantic prefixes we want to expose to the app.
const SEMANTIC_PREFIXES = [
  "text-",
  "text",
  "background-",
  "border-",
  "border",
  "theme-",
  "status-",
  "action-",
  "code-",
  "highlight-",
  "shadow-",
  "mask-",
  "shimmer-",
  "frost-",
  "scrollbar-",
];

function isBaseToken(name: string): boolean {
  const n = name.replace(/^--/, "");
  return BASE_PREFIXES.some((p) => n.startsWith(p));
}

function isSemanticToken(name: string): boolean {
  if (isBaseToken(name)) return false;
  const n = name.replace(/^--/, "");
  return SEMANTIC_PREFIXES.some((p) => n === p || n.startsWith(p));
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  // --- Read sources ---------------------------------------------------------
  const colorsCss = stripComments(
    readFileSync(join(OPAL_STYLES, "colors.css"), "utf8"),
  );
  const typographyCssRaw = readFileSync(
    join(OPAL_STYLES, "typography.css"),
    "utf8",
  );
  const rootCss = stripComments(readFileSync(OPAL_ROOT_CSS, "utf8"));

  // --- Build light/base + dark declaration maps -----------------------------
  // All :root blocks form the light/base layer.
  const lightDecls = parseAllRootBlocks(colorsCss);
  // .dark overrides on top of the base palette (so dark semantic tokens can
  // still resolve base palette refs that only exist in :root).
  const darkOverrides = parseDeclarations(extractBlockBody(colorsCss, ".dark"));
  const darkDecls: Decls = { ...lightDecls, ...darkOverrides };

  // --- Collect the set of semantic token names ------------------------------
  const lightSemantic = Object.keys(lightDecls).filter((n) =>
    isSemanticToken(n),
  );
  const darkSemantic = Object.keys(darkOverrides).filter((n) =>
    isSemanticToken(n),
  );
  // Union of light + dark semantic tokens, both maps share the same key set.
  const keySet = new Set<string>([...lightSemantic, ...darkSemantic]);
  // Sorted for deterministic output.
  const keys = Array.from(keySet).sort();

  // --- Resolve to concrete values for each scheme ---------------------------
  const lightColors: Record<string, string> = {};
  const darkColors: Record<string, string> = {};
  for (const fullName of keys) {
    const key = fullName.replace(/^--/, "");
    // Light: token must exist in light decls; if only dark defined it, reuse dark.
    const lightRaw =
      lightDecls[fullName] ?? darkDecls[fullName];
    const darkRaw = darkDecls[fullName] ?? lightDecls[fullName];
    if (lightRaw === undefined || darkRaw === undefined) {
      throw new Error(`Token ${fullName} missing from both light and dark`);
    }
    lightColors[key] = resolveValue(lightRaw, lightDecls);
    darkColors[key] = resolveValue(darkRaw, darkDecls);
  }

  // --- Radii (root.css) -----------------------------------------------------
  const rootDecls = parseAllRootBlocks(rootCss);
  const radii: Record<string, number> = {};
  for (const [name, value] of Object.entries(rootDecls)) {
    const m = name.match(/^--border-radius-(.+)$/);
    if (!m) continue;
    const suffix = m[1]!;
    if (suffix === "full") {
      radii[suffix] = 9999;
      continue;
    }
    const remMatch = value.match(/^([\d.]+)rem$/);
    if (remMatch) {
      radii[suffix] = Math.round(parseFloat(remMatch[1]!) * 16);
    }
  }

  // --- Typography (typography.css) ------------------------------------------
  // Each Opal font family maps to the @expo-google-fonts package base name. The
  // *loaded* font family at runtime is weight-specific (e.g.
  // "HankenGrotesk_600SemiBold"), because that is how the weight-specific font
  // objects are registered by useAppFonts() in src/theme/fonts.ts. React Native
  // does not synthesize weights from a single family the way the web does, so we
  // must point fontFamily at the exact loaded face per weight.
  const FONT_FAMILY_MAP: Record<string, string> = {
    "--font-hanken-grotesk": "HankenGrotesk",
    "--font-dm-mono": "DMMono",
    "--font-kh-teka": "KHTeka",
  };

  // The Google-Fonts weight suffix for each standard numeric weight.
  const WEIGHT_SUFFIX: Record<number, string> = {
    100: "Thin",
    200: "ExtraLight",
    300: "Light",
    400: "Regular",
    500: "Medium",
    600: "SemiBold",
    700: "Bold",
    800: "ExtraBold",
    900: "Black",
  };

  // The numeric weights each family ACTUALLY ships in @expo-google-fonts, used
  // to round non-standard CSS weights (e.g. 450) to the nearest available face.
  // HankenGrotesk ships 100..900; DMMono only ships 300/400/500.
  const FAMILY_AVAILABLE_WEIGHTS: Record<string, number[]> = {
    HankenGrotesk: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    DMMono: [300, 400, 500],
    // KHTeka is not bundled as a Google font; fall back to the standard ladder
    // so the generator never throws if it ever appears in Opal CSS.
    KHTeka: [100, 200, 300, 400, 500, 600, 700, 800, 900],
  };

  /**
   * Round a CSS numeric weight to the nearest weight the family actually
   * provides. Ties (e.g. 450 between 400 and 500) round UP to the heavier
   * weight, matching the task spec (450 -> 500 Medium).
   */
  function nearestAvailableWeight(family: string, weight: number): number {
    const available = FAMILY_AVAILABLE_WEIGHTS[family] ?? [400];
    let best = available[0]!;
    let bestDist = Math.abs(weight - best);
    for (const w of available) {
      const dist = Math.abs(weight - w);
      // `<=` makes ties resolve to the heavier (later, sorted) weight.
      if (dist <= bestDist) {
        best = w;
        bestDist = dist;
      }
    }
    return best;
  }

  /**
   * Resolve the weight-specific loaded font-family name, e.g.
   * ("HankenGrotesk", 450) -> "HankenGrotesk_500Medium".
   */
  function loadedFontFamily(family: string, weight: number): string {
    const rounded = nearestAvailableWeight(family, weight);
    const suffix = WEIGHT_SUFFIX[rounded];
    if (!suffix) {
      throw new Error(
        `No weight suffix for rounded weight ${rounded} (family ${family})`,
      );
    }
    return `${family}_${rounded}${suffix}`;
  }

  const typographyCss = stripComments(typographyCssRaw);
  // NOTE: `fontWeight` is intentionally NOT part of the emitted preset. The
  // weight is fully encoded by the weight-specific `fontFamily` (e.g.
  // "HankenGrotesk_600SemiBold"). Emitting `fontWeight` as well risks Android
  // synthesizing an extra-bold face on top of an already-bold font file
  // ("double weighting"), so we drop it. fontFamily is the single source of
  // truth for weight.
  type Preset = {
    fontFamily: string;
    fontSize: number;
    lineHeight: number;
    letterSpacing: number;
  };
  const typography: Record<string, Preset> = {};
  // Track the set of weight-specific family names actually referenced, so the
  // verification step can confirm fonts.ts loads exactly these.
  const usedFontFamilies = new Set<string>();
  // Match `.font-<name> { ... }` class bodies. Skip selectors with extra
  // qualifiers (e.g. `.font-main-content-body strong`).
  const classRe = /\.font-([a-z0-9-]+)\s*\{([^}]*)\}/gi;
  let cm: RegExpExecArray | null;
  while ((cm = classRe.exec(typographyCss)) !== null) {
    const name = cm[1]!;
    const body = cm[2]!;
    const familyMatch = body.match(/font-family\s*:\s*var\(\s*(--font-[a-z-]+)\s*\)/i);
    const sizeMatch = body.match(/font-size\s*:\s*([\d.]+)px/i);
    const weightMatch = body.match(/font-weight\s*:\s*(\d+)/i);
    const lineMatch = body.match(/line-height\s*:\s*([\d.]+)px/i);
    const spacingMatch = body.match(/letter-spacing\s*:\s*(-?[\d.]+)px/i);
    // Require the core type properties; this also skips the `strong` rule.
    if (!sizeMatch || !weightMatch || !lineMatch) continue;
    const familyVar = familyMatch ? familyMatch[1]! : "--font-hanken-grotesk";
    const baseFamily = FONT_FAMILY_MAP[familyVar] ?? "HankenGrotesk";
    const cssWeight = parseInt(weightMatch[1]!, 10);
    const fontFamily = loadedFontFamily(baseFamily, cssWeight);
    usedFontFamilies.add(fontFamily);
    typography[name] = {
      // Weight-specific loaded face — see the Preset note above for why we omit
      // fontWeight here.
      fontFamily,
      fontSize: parseFloat(sizeMatch[1]!),
      lineHeight: parseFloat(lineMatch[1]!),
      letterSpacing: spacingMatch ? parseFloat(spacingMatch[1]!) : 0,
    };
  }

  // --- Emit files -----------------------------------------------------------
  mkdirSync(OUT_DIR, { recursive: true });

  // colors.ts
  const colorsTs =
    HEADER +
    "\nexport const lightColors = " +
    JSON.stringify(lightColors, null, 2) +
    " as const;\n\nexport const darkColors = " +
    JSON.stringify(darkColors, null, 2) +
    " as const;\n\nexport type ColorToken = keyof typeof lightColors;\n";
  writeFileSync(join(OUT_DIR, "colors.ts"), colorsTs);

  // radii.ts — emit with stable key ordering ("full" last).
  const sortedRadii: Record<string, number> = {};
  for (const k of Object.keys(radii).sort((a, b) => {
    if (a === "full") return 1;
    if (b === "full") return -1;
    return Number(a) - Number(b);
  })) {
    sortedRadii[k] = radii[k]!;
  }
  const radiiTs =
    HEADER +
    "\nexport const radii = " +
    JSON.stringify(sortedRadii, null, 2) +
    " as const;\n";
  writeFileSync(join(OUT_DIR, "radii.ts"), radiiTs);

  // typography.ts
  const typographyTs =
    HEADER +
    "\nexport const typography = " +
    JSON.stringify(typography, null, 2) +
    " as const;\n\nexport type TypographyPreset = keyof typeof typography;\n";
  writeFileSync(join(OUT_DIR, "typography.ts"), typographyTs);

  // nativewind-preset.js — colors map each token to its CSS var; ThemeProvider
  // supplies the runtime value via vars(). borderRadius uses concrete px.
  const presetColors: Record<string, string> = {};
  for (const fullName of keys) {
    const key = fullName.replace(/^--/, "");
    presetColors[key] = `var(--${key})`;
  }
  const presetBorderRadius: Record<string, number> = { ...sortedRadii };
  const presetJs =
    HEADER +
    "\nmodule.exports = " +
    JSON.stringify(
      {
        theme: {
          extend: {
            colors: presetColors,
            borderRadius: presetBorderRadius,
          },
        },
      },
      null,
      2,
    ) +
    ";\n";
  writeFileSync(join(OUT_DIR, "nativewind-preset.js"), presetJs);

  // --- Assertions (ground truth) --------------------------------------------
  function assertEq(actual: string, expected: string, label: string): void {
    if (actual !== expected) {
      throw new Error(
        `ASSERTION FAILED: ${label} === "${expected}" but got "${actual}"`,
      );
    }
  }

  assertEq(lightColors["text-05"]!, "#000000e5", 'lightColors["text-05"]');
  assertEq(
    lightColors["background-neutral-00"]!,
    "#ffffff",
    'lightColors["background-neutral-00"]',
  );
  assertEq(
    lightColors["background-neutral-01"]!,
    "#fafafa",
    'lightColors["background-neutral-01"]',
  );
  assertEq(lightColors["border-01"]!, "#e6e6e6", 'lightColors["border-01"]');
  assertEq(darkColors["text-05"]!, "#fffffff2", 'darkColors["text-05"]');
  assertEq(
    darkColors["background-neutral-00"]!,
    "#000000",
    'darkColors["background-neutral-00"]',
  );

  const tint01 = lightColors["background-tint-01"]!;
  if (tint01.includes("var(")) {
    throw new Error(
      `ASSERTION FAILED: background-tint-01 did not flatten; got "${tint01}"`,
    );
  }

  // --- Typography font-family assertions ------------------------------------
  // Every emitted preset must reference a weight-specific loaded face, never a
  // bare family name, and never a weight the family does not ship.
  for (const [name, preset] of Object.entries(typography)) {
    if (!/^[A-Za-z]+_\d{3}[A-Za-z]+$/.test(preset.fontFamily)) {
      throw new Error(
        `ASSERTION FAILED: typography["${name}"].fontFamily is not weight-specific: "${preset.fontFamily}"`,
      );
    }
  }
  // Spot-check the known 450->500 rounding case.
  assertEq(
    typography["main-content-body"]!.fontFamily,
    "HankenGrotesk_500Medium",
    'typography["main-content-body"].fontFamily',
  );
  assertEq(
    typography["main-content-mono"]!.fontFamily,
    "DMMono_400Regular",
    'typography["main-content-mono"].fontFamily',
  );
  assertEq(
    typography["heading-h1"]!.fontFamily,
    "HankenGrotesk_600SemiBold",
    'typography["heading-h1"].fontFamily',
  );

  // --- Report ---------------------------------------------------------------
  console.log("Opal -> mobile theme generation complete.");
  console.log("");
  console.log(`Semantic color tokens: ${keys.length}`);
  console.log(`Radii: ${Object.keys(radii).length}`);
  console.log(`Typography presets: ${Object.keys(typography).length}`);
  console.log("");
  console.log("Anchor values (asserted):");
  console.log(`  light text-05                = ${lightColors["text-05"]}`);
  console.log(
    `  light background-neutral-00  = ${lightColors["background-neutral-00"]}`,
  );
  console.log(
    `  light background-neutral-01  = ${lightColors["background-neutral-01"]}`,
  );
  console.log(`  light border-01              = ${lightColors["border-01"]}`);
  console.log(`  dark  text-05                = ${darkColors["text-05"]}`);
  console.log(
    `  dark  background-neutral-00  = ${darkColors["background-neutral-00"]}`,
  );
  console.log("");
  console.log(
    `  background-tint-01 resolved  = ${tint01} (light) / ${darkColors["background-tint-01"]} (dark)`,
  );
  console.log("");
  console.log(
    `Weight-specific font families referenced (${usedFontFamilies.size}):`,
  );
  for (const fam of Array.from(usedFontFamilies).sort()) {
    console.log(`  ${fam}`);
  }
  console.log("");
  console.log("All assertions passed.");
  console.log("");
  console.log("Wrote:");
  console.log(`  ${join(OUT_DIR, "colors.ts")}`);
  console.log(`  ${join(OUT_DIR, "radii.ts")}`);
  console.log(`  ${join(OUT_DIR, "typography.ts")}`);
  console.log(`  ${join(OUT_DIR, "nativewind-preset.js")}`);
}

main();
