// Opal CSS -> mobile theme bridge. Run with `bun scripts/generate-theme.ts`.
// NativeWind cannot resolve var() indirection at the value level, so every
// color is recursively flattened to a concrete hex.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const MOBILE_ROOT = join(__dirname, "..");
const OPAL_STYLES = join(
  MOBILE_ROOT,
  "..",
  "web",
  "lib",
  "opal",
  "src",
  "styles",
);
const OPAL_ROOT_CSS = join(MOBILE_ROOT, "..", "web", "lib", "opal", "src", "root.css");
const OUT_DIR = join(MOBILE_ROOT, "src", "theme", "generated");

const HEADER =
  "// AUTO-GENERATED by mobile/scripts/generate-theme.ts from Opal CSS. Do not edit by hand.\n";

type Decls = Record<string, string>;

// Strip comments so they don't confuse the brace/declaration scanner.
function stripComments(css: string): string {
  return css.replace(/\/\*[\s\S]*?\*\//g, "");
}

// Later declarations override earlier ones (CSS cascade within a layer).
function parseDeclarations(block: string): Decls {
  const decls: Decls = {};
  const re = /(--[a-z0-9-]+)\s*:\s*([^;]+);/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(block)) !== null) {
    const name = m[1]!.trim();
    const value = m[2]!.trim();
    decls[name] = value;
  }
  return decls;
}

// Body of the first selector block matching `selector` (e.g. ".dark"), or "".
function extractBlockBody(css: string, selector: string): string {
  const idx = css.indexOf(selector);
  if (idx === -1) return "";
  const braceStart = css.indexOf("{", idx);
  if (braceStart === -1) return "";
  let depth = 0;
  for (let i = braceStart; i < css.length; i++) {
    const ch = css[i];
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) return css.slice(braceStart + 1, i);
    }
  }
  return "";
}

// All `:root { ... }` blocks in document order; later blocks override earlier.
function parseAllRootBlocks(css: string): Decls {
  const decls: Decls = {};
  const re = /:root\s*\{/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(css)) !== null) {
    const braceStart = m.index + m[0].length - 1;
    let depth = 0;
    let end = -1;
    for (let i = braceStart; i < css.length; i++) {
      const ch = css[i];
      if (ch === "{") depth++;
      else if (ch === "}") {
        depth--;
        if (depth === 0) {
          end = i;
          break;
        }
      }
    }
    if (end === -1) break;
    const body = css.slice(braceStart + 1, end);
    Object.assign(decls, parseDeclarations(body));
  }
  return decls;
}

// Recursively resolve a token to a concrete (non-var) value, following chains
// like background-tint-01 -> tint-02 -> stone-02 -> #fafafa.
function resolveValue(
  rawValue: string,
  decls: Decls,
  seen: Set<string> = new Set(),
): string {
  const value = rawValue.trim();
  const varMatch = value.match(/^var\(\s*(--[a-z0-9-]+)\s*\)$/i);
  if (!varMatch) {
    // Not a pure var() reference -> already concrete (hex, keyword, etc.).
    return value;
  }
  const refName = varMatch[1]!;
  if (seen.has(refName)) {
    throw new Error(`Cyclic var reference detected at ${refName}`);
  }
  const refValue = decls[refName];
  if (refValue === undefined) {
    throw new Error(`Unresolved var reference: ${refName}`);
  }
  seen.add(refName);
  return resolveValue(refValue, decls, seen);
}

// Raw base-palette prefixes that must NOT appear as semantic theme keys.
const BASE_PREFIXES = [
  "grey-",
  "alpha-grey-",
  "blue-",
  "green-",
  "red-",
  "orange-",
  "purple-",
  "neon-",
  "stone-",
  "chalk-",
  "slate-",
  "tint-",
  "onyx-",
  "font-",
];

const SEMANTIC_PREFIXES = [
  "text-",
  "text",
  "background-",
  "border-",
  "border",
  "theme-",
  "status-",
  "action-",
  "code-",
  "highlight-",
  "shadow-",
  "mask-",
  "shimmer-",
  "frost-",
  "scrollbar-",
];

function isBaseToken(name: string): boolean {
  const n = name.replace(/^--/, "");
  return BASE_PREFIXES.some((p) => n.startsWith(p));
}

function isSemanticToken(name: string): boolean {
  if (isBaseToken(name)) return false;
  const n = name.replace(/^--/, "");
  return SEMANTIC_PREFIXES.some((p) => n === p || n.startsWith(p));
}

function main(): void {
  const colorsCss = stripComments(
    readFileSync(join(OPAL_STYLES, "colors.css"), "utf8"),
  );
  const typographyCssRaw = readFileSync(
    join(OPAL_STYLES, "typography.css"),
    "utf8",
  );
  const rootCss = stripComments(readFileSync(OPAL_ROOT_CSS, "utf8"));

  const lightDecls = parseAllRootBlocks(colorsCss);
  // .dark overrides layer on the base palette so dark semantic tokens can still
  // resolve base palette refs that only exist in :root.
  const darkOverrides = parseDeclarations(extractBlockBody(colorsCss, ".dark"));
  const darkDecls: Decls = { ...lightDecls, ...darkOverrides };

  const lightSemantic = Object.keys(lightDecls).filter((n) =>
    isSemanticToken(n),
  );
  const darkSemantic = Object.keys(darkOverrides).filter((n) =>
    isSemanticToken(n),
  );
  const keySet = new Set<string>([...lightSemantic, ...darkSemantic]);
  const keys = Array.from(keySet).sort();

  const lightColors: Record<string, string> = {};
  const darkColors: Record<string, string> = {};
  for (const fullName of keys) {
    const key = fullName.replace(/^--/, "");
    // If a token is only defined in dark, reuse it for light (and vice versa).
    const lightRaw =
      lightDecls[fullName] ?? darkDecls[fullName];
    const darkRaw = darkDecls[fullName] ?? lightDecls[fullName];
    if (lightRaw === undefined || darkRaw === undefined) {
      throw new Error(`Token ${fullName} missing from both light and dark`);
    }
    lightColors[key] = resolveValue(lightRaw, lightDecls);
    darkColors[key] = resolveValue(darkRaw, darkDecls);
  }

  // Radii (root.css)
  const rootDecls = parseAllRootBlocks(rootCss);
  const radii: Record<string, number> = {};
  for (const [name, value] of Object.entries(rootDecls)) {
    const m = name.match(/^--border-radius-(.+)$/);
    if (!m) continue;
    const suffix = m[1]!;
    if (suffix === "full") {
      radii[suffix] = 9999;
      continue;
    }
    const remMatch = value.match(/^([\d.]+)rem$/);
    if (remMatch) {
      radii[suffix] = Math.round(parseFloat(remMatch[1]!) * 16);
    }
  }

  // Typography (typography.css). RN does not synthesize weights from a single
  // family the way the web does, so the loaded family must be weight-specific
  // (e.g. "HankenGrotesk_600SemiBold") matching what useAppFonts() registers.
  const FONT_FAMILY_MAP: Record<string, string> = {
    "--font-hanken-grotesk": "HankenGrotesk",
    "--font-dm-mono": "DMMono",
    "--font-kh-teka": "KHTeka",
  };

  const WEIGHT_SUFFIX: Record<number, string> = {
    100: "Thin",
    200: "ExtraLight",
    300: "Light",
    400: "Regular",
    500: "Medium",
    600: "SemiBold",
    700: "Bold",
    800: "ExtraBold",
    900: "Black",
  };

  // Weights each family actually ships in @expo-google-fonts, used to round
  // non-standard CSS weights (e.g. 450) to the nearest available face.
  const FAMILY_AVAILABLE_WEIGHTS: Record<string, number[]> = {
    HankenGrotesk: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    DMMono: [300, 400, 500],
    // KHTeka is not a Google font; fall back to the standard ladder so the
    // generator never throws if it appears in Opal CSS.
    KHTeka: [100, 200, 300, 400, 500, 600, 700, 800, 900],
  };

  // Round to the nearest available weight; ties (e.g. 450) round UP (-> 500).
  function nearestAvailableWeight(family: string, weight: number): number {
    const available = FAMILY_AVAILABLE_WEIGHTS[family] ?? [400];
    let best = available[0]!;
    let bestDist = Math.abs(weight - best);
    for (const w of available) {
      const dist = Math.abs(weight - w);
      // `<=` makes ties resolve to the heavier (later, sorted) weight.
      if (dist <= bestDist) {
        best = w;
        bestDist = dist;
      }
    }
    return best;
  }

  // e.g. ("HankenGrotesk", 450) -> "HankenGrotesk_500Medium".
  function loadedFontFamily(family: string, weight: number): string {
    const rounded = nearestAvailableWeight(family, weight);
    const suffix = WEIGHT_SUFFIX[rounded];
    if (!suffix) {
      throw new Error(
        `No weight suffix for rounded weight ${rounded} (family ${family})`,
      );
    }
    return `${family}_${rounded}${suffix}`;
  }

  const typographyCss = stripComments(typographyCssRaw);
  // No `fontWeight` in the preset: weight is fully encoded by the weight-specific
  // fontFamily. Emitting it too risks Android double-weighting (synthesizing an
  // extra-bold face on top of an already-bold file).
  type Preset = {
    fontFamily: string;
    fontSize: number;
    lineHeight: number;
    letterSpacing: number;
  };
  const typography: Record<string, Preset> = {};
  // Family names referenced, so verification can confirm fonts.ts loads these.
  const usedFontFamilies = new Set<string>();
  // Match `.font-<name> { ... }`; skip qualified selectors (e.g. `... strong`).
  const classRe = /\.font-([a-z0-9-]+)\s*\{([^}]*)\}/gi;
  let cm: RegExpExecArray | null;
  while ((cm = classRe.exec(typographyCss)) !== null) {
    const name = cm[1]!;
    const body = cm[2]!;
    const familyMatch = body.match(/font-family\s*:\s*var\(\s*(--font-[a-z-]+)\s*\)/i);
    const sizeMatch = body.match(/font-size\s*:\s*([\d.]+)px/i);
    const weightMatch = body.match(/font-weight\s*:\s*(\d+)/i);
    const lineMatch = body.match(/line-height\s*:\s*([\d.]+)px/i);
    const spacingMatch = body.match(/letter-spacing\s*:\s*(-?[\d.]+)px/i);
    // Require the core type properties; this also skips the `strong` rule.
    if (!sizeMatch || !weightMatch || !lineMatch) continue;
    const familyVar = familyMatch ? familyMatch[1]! : "--font-hanken-grotesk";
    const baseFamily = FONT_FAMILY_MAP[familyVar] ?? "HankenGrotesk";
    const cssWeight = parseInt(weightMatch[1]!, 10);
    const fontFamily = loadedFontFamily(baseFamily, cssWeight);
    usedFontFamilies.add(fontFamily);
    typography[name] = {
      fontFamily,
      fontSize: parseFloat(sizeMatch[1]!),
      lineHeight: parseFloat(lineMatch[1]!),
      letterSpacing: spacingMatch ? parseFloat(spacingMatch[1]!) : 0,
    };
  }

  mkdirSync(OUT_DIR, { recursive: true });

  const colorsTs =
    HEADER +
    "\nexport const lightColors = " +
    JSON.stringify(lightColors, null, 2) +
    " as const;\n\nexport const darkColors = " +
    JSON.stringify(darkColors, null, 2) +
    " as const;\n\nexport type ColorToken = keyof typeof lightColors;\n";
  writeFileSync(join(OUT_DIR, "colors.ts"), colorsTs);

  // Stable key ordering ("full" last).
  const sortedRadii: Record<string, number> = {};
  for (const k of Object.keys(radii).sort((a, b) => {
    if (a === "full") return 1;
    if (b === "full") return -1;
    return Number(a) - Number(b);
  })) {
    sortedRadii[k] = radii[k]!;
  }
  const radiiTs =
    HEADER +
    "\nexport const radii = " +
    JSON.stringify(sortedRadii, null, 2) +
    " as const;\n";
  writeFileSync(join(OUT_DIR, "radii.ts"), radiiTs);

  const typographyTs =
    HEADER +
    "\nexport const typography = " +
    JSON.stringify(typography, null, 2) +
    " as const;\n\nexport type TypographyPreset = keyof typeof typography;\n";
  writeFileSync(join(OUT_DIR, "typography.ts"), typographyTs);

  // Colors map each token to its CSS var; ThemeProvider supplies the runtime
  // value via vars(). borderRadius uses concrete px.
  const presetColors: Record<string, string> = {};
  for (const fullName of keys) {
    const key = fullName.replace(/^--/, "");
    presetColors[key] = `var(--${key})`;
  }
  const presetBorderRadius: Record<string, number> = { ...sortedRadii };
  const presetJs =
    HEADER +
    "\nmodule.exports = " +
    JSON.stringify(
      {
        theme: {
          extend: {
            colors: presetColors,
            borderRadius: presetBorderRadius,
          },
        },
      },
      null,
      2,
    ) +
    ";\n";
  writeFileSync(join(OUT_DIR, "nativewind-preset.js"), presetJs);

  // Assertions (ground truth)
  function assertEq(actual: string, expected: string, label: string): void {
    if (actual !== expected) {
      throw new Error(
        `ASSERTION FAILED: ${label} === "${expected}" but got "${actual}"`,
      );
    }
  }

  assertEq(lightColors["text-05"]!, "#000000e5", 'lightColors["text-05"]');
  assertEq(
    lightColors["background-neutral-00"]!,
    "#ffffff",
    'lightColors["background-neutral-00"]',
  );
  assertEq(
    lightColors["background-neutral-01"]!,
    "#fafafa",
    'lightColors["background-neutral-01"]',
  );
  assertEq(lightColors["border-01"]!, "#e6e6e6", 'lightColors["border-01"]');
  assertEq(darkColors["text-05"]!, "#fffffff2", 'darkColors["text-05"]');
  assertEq(
    darkColors["background-neutral-00"]!,
    "#000000",
    'darkColors["background-neutral-00"]',
  );

  const tint01 = lightColors["background-tint-01"]!;
  if (tint01.includes("var(")) {
    throw new Error(
      `ASSERTION FAILED: background-tint-01 did not flatten; got "${tint01}"`,
    );
  }

  // Every preset must reference a weight-specific face, never a bare family.
  for (const [name, preset] of Object.entries(typography)) {
    if (!/^[A-Za-z]+_\d{3}[A-Za-z]+$/.test(preset.fontFamily)) {
      throw new Error(
        `ASSERTION FAILED: typography["${name}"].fontFamily is not weight-specific: "${preset.fontFamily}"`,
      );
    }
  }
  // Spot-check the known 450->500 rounding case.
  assertEq(
    typography["main-content-body"]!.fontFamily,
    "HankenGrotesk_500Medium",
    'typography["main-content-body"].fontFamily',
  );
  assertEq(
    typography["main-content-mono"]!.fontFamily,
    "DMMono_400Regular",
    'typography["main-content-mono"].fontFamily',
  );
  assertEq(
    typography["heading-h1"]!.fontFamily,
    "HankenGrotesk_600SemiBold",
    'typography["heading-h1"].fontFamily',
  );

  console.log("Opal -> mobile theme generation complete.");
  console.log("");
  console.log(`Semantic color tokens: ${keys.length}`);
  console.log(`Radii: ${Object.keys(radii).length}`);
  console.log(`Typography presets: ${Object.keys(typography).length}`);
  console.log("");
  console.log("Anchor values (asserted):");
  console.log(`  light text-05                = ${lightColors["text-05"]}`);
  console.log(
    `  light background-neutral-00  = ${lightColors["background-neutral-00"]}`,
  );
  console.log(
    `  light background-neutral-01  = ${lightColors["background-neutral-01"]}`,
  );
  console.log(`  light border-01              = ${lightColors["border-01"]}`);
  console.log(`  dark  text-05                = ${darkColors["text-05"]}`);
  console.log(
    `  dark  background-neutral-00  = ${darkColors["background-neutral-00"]}`,
  );
  console.log("");
  console.log(
    `  background-tint-01 resolved  = ${tint01} (light) / ${darkColors["background-tint-01"]} (dark)`,
  );
  console.log("");
  console.log(
    `Weight-specific font families referenced (${usedFontFamilies.size}):`,
  );
  for (const fam of Array.from(usedFontFamilies).sort()) {
    console.log(`  ${fam}`);
  }
  console.log("");
  console.log("All assertions passed.");
  console.log("");
  console.log("Wrote:");
  console.log(`  ${join(OUT_DIR, "colors.ts")}`);
  console.log(`  ${join(OUT_DIR, "radii.ts")}`);
  console.log(`  ${join(OUT_DIR, "typography.ts")}`);
  console.log(`  ${join(OUT_DIR, "nativewind-preset.js")}`);
}

main();
