"""Add new field in api_key

Revision ID: 08e30e1ec8e4
Revises: 54f3af073585
Create Date: 2025-12-03 13:36:06.942701

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "08e30e1ec8e4"
down_revision = "54f3af073585"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "api_key",
        sa.Column(
            "is_new_user",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false')
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_key", "is_new_user")