"""set_unique_name_validator

Revision ID: 14f643b653f6
Revises: 53d4656de077
Create Date: 2025-10-10 11:39:54.409299

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "14f643b653f6"
down_revision = "53d4656de077"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_validator_name", "validator", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_validator_name", "validator", type_="unique")
    # ### end Alembic commands ###
