"""add table validators__user_group and column is_public in validator

Revision ID: 521e9ae36258
Revises: 2b9492e28665
Create Date: 2025-10-09 09:45:49.342782

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "521e9ae36258"
down_revision = "2b9492e28665"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "validator__user_group",
        sa.Column("validator_id", sa.Integer(), nullable=False),
        sa.Column("user_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_group_id"],
            ["user_group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["validator_id"],
            ["validator.id"],
        ),
        sa.PrimaryKeyConstraint("validator_id", "user_group_id"),
    )
    op.add_column(
        "validator", sa.Column("is_public", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("validator", "is_public")
    op.drop_table("validator__user_group")
    # ### end Alembic commands ###
