"""add_cascade_delete_for_persona__validator_and_validator__user_group

Revision ID: 53d4656de077
Revises: 521e9ae36258
Create Date: 2025-10-10 11:01:12.650316

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "53d4656de077"
down_revision = "521e9ae36258"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "persona__validator_persona_id_fkey",
        "persona__validator",
        type_="foreignkey",
    )
    op.drop_constraint(
        "persona__validator_validator_id_fkey",
        "persona__validator",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "persona__validator_persona_id_fkey",
        "persona__validator",
        "persona",
        ["persona_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "persona__validator_validator_id_fkey",
        "persona__validator",
        "validator",
        ["validator_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "validator__user_group_validator_id_fkey",
        "validator__user_group",
        type_="foreignkey",
    )
    op.drop_constraint(
        "validator__user_group_user_group_id_fkey",
        "validator__user_group",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "validator__user_group_validator_id_fkey",
        "validator__user_group",
        "validator",
        ["validator_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "validator__user_group_user_group_id_fkey",
        "validator__user_group",
        "user_group",
        ["user_group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("validator__user_group_user_group_id_fkey", "validator__user_group", type_="foreignkey")
    op.drop_constraint("validator__user_group_validator_id_fkey", "validator__user_group", type_="foreignkey")
    op.create_foreign_key(
        "validator__user_group_user_group_id_fkey",
        "validator__user_group",
        "user_group",
        ["user_group_id"],
        ["id"],
    )
    op.create_foreign_key(
        "validator__user_group_validator_id_fkey",
        "validator__user_group",
        "validator",
        ["validator_id"],
        ["id"],
    )
    op.drop_constraint("persona__validator_validator_id_fkey", "persona__validator", type_="foreignkey")
    op.drop_constraint("persona__validator_persona_id_fkey", "persona__validator", type_="foreignkey")
    op.create_foreign_key(
        "persona__validator_validator_id_fkey",
        "persona__validator",
        "validator",
        ["validator_id"],
        ["id"],
    )
    op.create_foreign_key(
        "persona__validator_persona_id_fkey",
        "persona__validator",
        "persona",
        ["persona_id"],
        ["id"],
    )
    # ### end Alembic commands ###
