"""add_column_include_llm__and__add_llm_provider_to_validator

Revision ID: 5cc54b4cc28b
Revises: 70b0ac5dfc14
Create Date: 2025-10-21 13:35:41.065143

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "5cc54b4cc28b"
down_revision = "70b0ac5dfc14"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "validator", sa.Column("include_llm", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "validator", sa.Column("llm_provider_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "validator", "llm_provider", ["llm_provider_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("validator_llm_provider_id_fkey", "validator", type_="foreignkey")
    op.drop_column("validator", "llm_provider_id")
    op.drop_column("validator", "include_llm")

    # ### end Alembic commands ###
