"""add telegram tabls

Revision ID: 5eb9b14f4656
Revises: 81f65b7f25ba
Create Date: 2024-10-28 13:14:13.967004

"""
import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5eb9b14f4656'
down_revision = '81f65b7f25ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_user_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('model', sa.JSON(), nullable=True),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('telegram_user_api_key',
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('api_key'),
    sa.UniqueConstraint('api_key')
    )
    op.create_foreign_key(None, 'api_key', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'api_key', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_user_api_key')
    op.drop_table('telegram_user_settings')
    # ### end Alembic commands ###
