"""change_type_config_in_validator

Revision ID: 616b3124c8fa
Revises: 14f643b653f6
Create Date: 2025-10-13 15:07:05.434826

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "616b3124c8fa"
down_revision = "14f643b653f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'validator',
        'config',
        type_=sa.LargeBinary(),
        postgresql_using='config::text::bytea'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'validator',
        'config',
        type_=postgresql.JSONB(),
        postgresql_using='config::text::jsonb'
    )
    # ### end Alembic commands ###
