"""add_validator_table_and_persona__validator_table

Revision ID: 70b0ac5dfc14
Revises: 5eb9b14f4656
Create Date: 2025-10-14 12:53:56.320116

"""

from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "70b0ac5dfc14"
down_revision = "5eb9b14f4656"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "validator",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "user_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "validator_type",
            sa.Enum(
                "DETECT_PII",
                "TOXIC_LANGUAGE",
                "NSFW_TEXT",
                "SENSITIVE_TOPIC",
                "BAN_LIST",
                "TEXT_STYLE",
                "VALID_LENGTH",
                "VALID_JSON",
                "COMPETITOR_CHECK",
                "HALLUCINATION",
                "TOPIC_RESTRICTION",
                "JAILBREAKING",
                name="validatortype",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_validator_name"),
    )
    op.create_table(
        "persona__validator",
        sa.Column("persona_id", sa.Integer(), nullable=False),
        sa.Column("validator_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["persona.id"],
            name="persona__validator_persona_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["validator_id"],
            ["validator.id"],
            name="persona__validator_validator_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("persona_id", "validator_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("persona__validator")
    op.drop_table("validator")
    # ### end Alembic commands ###
