"""Add persona pipeline_id and use_default

Revision ID: e58d392624d2
Revises: cf90764725d8
Create Date: 2025-04-04 10:56:39.769294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e58d392624d2"
down_revision = "cf90764725d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persona", sa.Column("pipeline_id", sa.String(), nullable=True)
    )
    op.add_column("persona", sa.Column('template_file', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("persona", "pipeline_id")
    op.drop_column("persona", 'template_file')
    # ### end Alembic commands ###
