"""Add persona pipeline_id and use_default

Revision ID: e58d392624d2
Revises: bc9771dccadf
Create Date: 2024-08-20 09:57:34.554121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e58d392624d2"
down_revision = "cf90764725d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persona", sa.Column("pipeline_id", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("persona", "pipeline_id")
    # ### end Alembic commands ###
