name: "Docker Merge Manifest"
description: "Download platform digests and create multi-platform manifest"
inputs:
  registry-image:
    description: "Registry image name (e.g., onyxdotapp/onyx-backend)"
    required: true
  ecr-cache-registry:
    description: "ECR cache registry for runs-on"
    required: true
  name:
    description: "Name prefix for artifacts to download (e.g., backend, web)"
    required: true
  tags:
    description: "Metadata tags configuration (passed to metadata-action)"
    required: true
  docker-username:
    description: "Docker Hub username"
    required: true
  docker-password:
    description: "Docker Hub password/token"
    required: true
  is-dry-run:
    description: "Whether this is a dry run (workflow_dispatch)"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Download digests
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # ratchet:actions/download-artifact@v4
      with:
        path: ${{ runner.temp }}/digests
        pattern: digests-${{ inputs.name }}-*
        merge-multiple: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # ratchet:docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # ratchet:docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # ratchet:docker/metadata-action@v5
      with:
        images: ${{ inputs.is-dry-run == 'true' && inputs.ecr-cache-registry || inputs.registry-image }}
        flavor: |
          latest=false
        tags: ${{ inputs.tags }}

    - name: Create manifest list and push
      shell: bash
      working-directory: ${{ runner.temp }}/digests
      env:
        IMAGE_REPO: ${{ inputs.is-dry-run == 'true' && inputs.ecr-cache-registry || inputs.registry-image }}
      run: |
        docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf "${IMAGE_REPO}@sha256:%s " *)

    - name: Inspect image
      shell: bash
      env:
        IMAGE_REPO: ${{ inputs.is-dry-run == 'true' && inputs.ecr-cache-registry || inputs.registry-image }}
        VERSION: ${{ steps.meta.outputs.version }}
      run: |
        docker buildx imagetools inspect "${IMAGE_REPO}:${VERSION}"
