// Chrome message types
export const CHROME_MESSAGE = {
  PREFERENCES_UPDATED: "PREFERENCES_UPDATED",
  ONYX_APP_LOADED: "ONYX_APP_LOADED",
  SET_DEFAULT_NEW_TAB: "SET_DEFAULT_NEW_TAB",
  LOAD_NEW_CHAT_PAGE: "LOAD_NEW_CHAT_PAGE",
  LOAD_NEW_PAGE: "LOAD_NEW_PAGE",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  TAB_READING_ENABLED: "TAB_READING_ENABLED",
  TAB_READING_DISABLED: "TAB_READING_DISABLED",
  TAB_URL_UPDATED: "TAB_URL_UPDATED",
};

export const SUBMIT_MESSAGE_TYPES = {
  PAGE_CHANGE: "PAGE_CHANGE",
};

export const LocalStorageKeys = {
  THEME: "onyxTheme",
  LIGHT_BG_URL: "lightBgUrl",
  DARK_BG_URL: "darkBgUrl",
  SHORTCUTS: "shortCuts",
  SHOW_SHORTCUTS: "showShortcuts",
  USE_ONYX_AS_NEW_TAB: "useOnyxAsDefaultNewTab",
};

export const NO_AUTH_USER_ID = "__no_auth_user__";
