import type { SVGProps } from "react";

declare module "@opal" {
  export const OPAL_VERSION: string;
  export interface IconProps extends SVGProps<SVGSVGElement> {
    className?: string;
    size?: number;
    title?: string;
    color?: string;
  }
}

declare module "@opal/icons" {
  import type { IconProps } from "@opal";

  export type IconComponent = (props: IconProps) => JSX.Element;
  export { IconProps };
  export type { IconComponent };
  export const SvgActions: IconComponent;
  export const SvgActivity: IconComponent;
  export const SvgAddLines: IconComponent;
  export const SvgAlertCircle: IconComponent;
  export const SvgAlertTriangle: IconComponent;
  export const SvgArrowDownDot: IconComponent;
  export const SvgArrowExchange: IconComponent;
  export const SvgArrowLeftDot: IconComponent;
  export const SvgArrowLeft: IconComponent;
  export const SvgArrowRightCircle: IconComponent;
  export const SvgArrowRightDot: IconComponent;
  export const SvgArrowRight: IconComponent;
  export const SvgArrowUpDot: IconComponent;
  export const SvgArrowUpRight: IconComponent;
  export const SvgArrowUp: IconComponent;
  export const SvgArrowWallRight: IconComponent;
  export const SvgAws: IconComponent;
  export const SvgBarChart: IconComponent;
  export const SvgBell: IconComponent;
  export const SvgBracketCurly: IconComponent;
  export const SvgBubbleText: IconComponent;
  export const SvgCalendar: IconComponent;
  export const SvgCheckCircle: IconComponent;
  export const SvgCheckSquare: IconComponent;
  export const SvgCheck: IconComponent;
  export const SvgChevronDownSmall: IconComponent;
  export const SvgChevronDown: IconComponent;
  export const SvgChevronLeft: IconComponent;
  export const SvgChevronRight: IconComponent;
  export const SvgChevronUpSmall: IconComponent;
  export const SvgChevronUp: IconComponent;
  export const SvgClaude: IconComponent;
  export const SvgClipboard: IconComponent;
  export const SvgClock: IconComponent;
  export const SvgCloud: IconComponent;
  export const SvgCode: IconComponent;
  export const SvgCopy: IconComponent;
  export const SvgCornerRightUpDot: IconComponent;
  export const SvgCpu: IconComponent;
  export const SvgDevKit: IconComponent;
  export const SvgDownloadCloud: IconComponent;
  export const SvgEditBig: IconComponent;
  export const SvgEdit: IconComponent;
  export const SvgExternalLink: IconComponent;
  export const SvgEyeClosed: IconComponent;
  export const SvgEye: IconComponent;
  export const SvgFileText: IconComponent;
  export const SvgFiles: IconComponent;
  export const SvgFilter: IconComponent;
  export const SvgFold: IconComponent;
  export const SvgFolderIn: IconComponent;
  export const SvgFolderOpen: IconComponent;
  export const SvgFolderPartialOpen: IconComponent;
  export const SvgFolderPlus: IconComponent;
  export const SvgFolder: IconComponent;
  export const SvgGlobe: IconComponent;
  export const SvgHardDrive: IconComponent;
  export const SvgHeadsetMic: IconComponent;
  export const SvgHourglass: IconComponent;
  export const SvgImage: IconComponent;
  export const SvgImport: IconComponent;
  export const SvgKey: IconComponent;
  export const SvgLightbulbSimple: IconComponent;
  export const SvgLineChartUp: IconComponent;
  export const SvgLink: IconComponent;
  export const SvgLinkedDots: IconComponent;
  export const SvgLoader: IconComponent;
  export const SvgLock: IconComponent;
  export const SvgLogOut: IconComponent;
  export const SvgMaximize2: IconComponent;
  export const SvgMenu: IconComponent;
  export const SvgMinusCircle: IconComponent;
  export const SvgMinus: IconComponent;
  export const SvgMoon: IconComponent;
  export const SvgMoreHorizontal: IconComponent;
  export const SvgOllama: IconComponent;
  export const SvgOnyxLogo: IconComponent;
  export const SvgOnyxOctagon: IconComponent;
  export const SvgOpenai: IconComponent;
  export const SvgOpenrouter: IconComponent;
  export const SvgOrganization: IconComponent;
  export const SvgPaperclip: IconComponent;
  export const SvgPauseCircle: IconComponent;
  export const SvgPieChart: IconComponent;
  export const SvgPin: IconComponent;
  export const SvgPinned: IconComponent;
  export const SvgPlayCircle: IconComponent;
  export const SvgPlug: IconComponent;
  export const SvgPlusCircle: IconComponent;
  export const SvgPlus: IconComponent;
  export const SvgQuoteEnd: IconComponent;
  export const SvgQuoteStart: IconComponent;
  export const SvgRefreshCw: IconComponent;
  export const SvgSearchMenu: IconComponent;
  export const SvgSearch: IconComponent;
  export const SvgServer: IconComponent;
  export const SvgSettings: IconComponent;
  export const SvgShare: IconComponent;
  export const SvgShield: IconComponent;
  export const SvgSidebar: IconComponent;
  export const SvgSlack: IconComponent;
  export const SvgSlash: IconComponent;
  export const SvgSliders: IconComponent;
  export const SvgSparkle: IconComponent;
  export const SvgStep1: IconComponent;
  export const SvgStep2: IconComponent;
  export const SvgStep3End: IconComponent;
  export const SvgStep3: IconComponent;
  export const SvgStopCircle: IconComponent;
  export const SvgStop: IconComponent;
  export const SvgSun: IconComponent;
  export const SvgThumbsDown: IconComponent;
  export const SvgThumbsUp: IconComponent;
  export const SvgTrash: IconComponent;
  export const SvgTwoLineSmall: IconComponent;
  export const SvgUnplug: IconComponent;
  export const SvgUploadCloud: IconComponent;
  export const SvgUserPlus: IconComponent;
  export const SvgUser: IconComponent;
  export const SvgUsers: IconComponent;
  export const SvgWallet: IconComponent;
  export const SvgWorkflow: IconComponent;
  export const SvgXCircle: IconComponent;
  export const SvgXOctagon: IconComponent;
  export const SvgX: IconComponent;
  export const SvgZoomIn: IconComponent;
  export const SvgZoomOut: IconComponent;
}

declare module "@opal/types/icons" {
  export * from "@opal";
}
