# /// script
# requires-python = ">=3.11"
# dependencies = ["ruamel.yaml>=0.18"]
# ///
"""Generate docker-compose variant files from the main docker-compose.yml.

Each variant defines which services to remove, which to add, which
commented-out blocks to strip, and where to write the output. The main
docker-compose.yml is the single source of truth — variants are derived
from it so shared service definitions never drift.

Usage:
    uv run generate_compose_variants.py                   # generate all variants
    uv run generate_compose_variants.py headless           # generate one variant
    uv run generate_compose_variants.py --check            # check all (CI / pre-commit)
    uv run generate_compose_variants.py --check headless   # check one
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from dataclasses import dataclass
from dataclasses import field
from io import StringIO
from pathlib import Path

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap


# ---------------------------------------------------------------------------
# Variant configuration
# ---------------------------------------------------------------------------


@dataclass
class Variant:
    """Describes how to derive a compose file from the main docker-compose.yml."""

    # Variant name (used as CLI argument).
    name: str
    # Subdirectory (relative to SCRIPT_DIR) for the output file.
    output_dir: str
    # Header comment placed at the top of the generated file.
    header: str
    # Service names to remove from the base compose file.
    remove_services: set[str] = field(default_factory=set)
    # YAML strings defining services to add. Each string is a single-service
    # YAML document (e.g. "cli_server:\n  image: ..."). Paths inside these
    # definitions should already be relative to the output subdirectory.
    add_services_yaml: list[str] = field(default_factory=list)
    # Volume names to add to the top-level volumes section.
    add_volumes: list[str] = field(default_factory=list)
    # Commented-out service block names to strip (regex-matched).
    strip_commented_blocks: list[str] = field(default_factory=list)
    # Environment overrides to apply to existing services.
    # Maps service_name -> {env_var: value}. Added/overridden in the
    # service's `environment` list.
    env_overrides: dict[str, dict[str, str]] = field(default_factory=dict)


VARIANTS: dict[str, Variant] = {}


def register(v: Variant) -> Variant:
    VARIANTS[v.name] = v
    return v


# -- headless ---------------------------------------------------------------

register(
    Variant(
        name="headless",
        output_dir="headless",
        header="""\
# =============================================================================
# ONYX HEADLESS DOCKER COMPOSE (AUTO-GENERATED)
# =============================================================================
# This file is generated by generate_compose_variants.py from docker-compose.yml.
# DO NOT EDIT THIS FILE DIRECTLY — your changes will be overwritten.
#
# To regenerate:
#   cd deployment/docker_compose
#   uv run generate_compose_variants.py headless
#
# Usage:
#   cd deployment/docker_compose/headless
#   docker compose up -d
#
# Connect via SSH:
#   ssh localhost -p 2222
# =============================================================================

""",
        remove_services={"web_server", "nginx"},
        add_services_yaml=[
            """\
cli_server:
  image: ${ONYX_CLI_IMAGE:-onyxdotapp/onyx-cli:${IMAGE_TAG:-latest}}
  build:
    context: ../../../cli
    dockerfile: Dockerfile
  command: ["serve", "--host", "0.0.0.0", "--port", "2222"]
  depends_on:
    - api_server
  restart: unless-stopped
  ports:
    - "${ONYX_SSH_PORT:-2222}:2222"
  environment:
    - ONYX_SERVER_URL=http://api_server:8080
  volumes:
    - cli_config:/home/onyx/.config
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "6"
"""
        ],
        add_volumes=["cli_config"],
        strip_commented_blocks=["mcp_server", "certbot"],
    )
)


# ---------------------------------------------------------------------------
# YAML helpers
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent
SOURCE = SCRIPT_DIR / "docker-compose.yml"


def load_yaml() -> tuple[YAML, CommentedMap]:
    yaml = YAML()
    yaml.preserve_quotes = True
    yaml.width = 4096  # avoid line wrapping
    with open(SOURCE) as f:
        data = yaml.load(f)
    return yaml, data


# ---------------------------------------------------------------------------
# Path adjustment (for output files living in a subdirectory)
# ---------------------------------------------------------------------------


def adjust_path(path: str) -> str:
    """Prepend ../ to a relative path to account for a subdirectory."""
    if path.startswith("./") or path.startswith("../"):
        return "../" + path
    if not path.startswith("/") and not path.startswith("$"):
        return "../" + path
    return path


def adjust_env_file(entry: dict | str) -> dict | str:
    if isinstance(entry, dict) and "path" in entry:
        entry["path"] = adjust_path(entry["path"])
    elif isinstance(entry, str):
        return adjust_path(entry)
    return entry


def adjust_build_context(build: CommentedMap | str) -> CommentedMap | str:
    if isinstance(build, CommentedMap) and "context" in build:
        build["context"] = adjust_path(build["context"])
    elif isinstance(build, str):
        return adjust_path(build)
    return build


def adjust_volume_bind(vol: str) -> str:
    """Adjust host path in a bind-mount volume string (host:container[:opts])."""
    parts = vol.split(":")
    if len(parts) >= 2:
        host_path = parts[0]
        if (
            host_path.startswith("./")
            or host_path.startswith("../")
            or (
                not host_path.startswith("/")
                and not host_path.startswith("$")
                and "/" in host_path
            )
        ):
            parts[0] = adjust_path(host_path)
            return ":".join(parts)
    return vol


def adjust_service_paths(service: CommentedMap) -> None:
    """Adjust all relative paths in a service definition for a subdirectory."""
    if "env_file" in service:
        ef = service["env_file"]
        if isinstance(ef, list):
            for i, entry in enumerate(ef):
                ef[i] = adjust_env_file(entry)
        elif isinstance(ef, (str, dict)):
            service["env_file"] = adjust_env_file(ef)

    if "build" in service:
        service["build"] = adjust_build_context(service["build"])

    if "volumes" in service:
        vols = service["volumes"]
        if isinstance(vols, list):
            for i, vol in enumerate(vols):
                if isinstance(vol, str):
                    vols[i] = adjust_volume_bind(vol)
                elif isinstance(vol, dict) and "source" in vol:
                    src = vol["source"]
                    if isinstance(src, str) and (
                        src.startswith("./") or src.startswith("../")
                    ):
                        vol["source"] = adjust_path(src)


# ---------------------------------------------------------------------------
# Text post-processing
# ---------------------------------------------------------------------------


def remove_commented_blocks(text: str, block_names: list[str]) -> str:
    """Remove commented-out service blocks matching *block_names*."""
    if not block_names:
        return text

    pattern = re.compile(
        r"^\s*#\s*(" + "|".join(re.escape(n) for n in block_names) + r"):"
    )

    lines = text.split("\n")
    result: list[str] = []
    skip = False
    blank_run = 0

    for line in lines:
        if pattern.match(line):
            skip = True
            # Remove preceding comment/blank lines that introduce the block
            while result and (
                result[-1].strip().startswith("#") or result[-1].strip() == ""
            ):
                result.pop()
            continue
        if skip:
            stripped = line.strip()
            if stripped.startswith("#") or stripped == "":
                continue
            else:
                skip = False

        if line.strip() == "":
            blank_run += 1
            if blank_run > 2:
                continue
        else:
            blank_run = 0

        result.append(line)

    return "\n".join(result)


def ensure_blank_line_before(text: str, pattern: str) -> str:
    """Ensure there is a blank line before lines matching *pattern*."""
    return re.sub(r"(\n)(" + pattern + r")", r"\1\n\2", text)


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------


def generate(variant: Variant) -> str:
    """Generate the variant's docker-compose.yml content."""
    yaml_inst, data = load_yaml()

    services = data["services"]

    # Remove services
    for name in variant.remove_services:
        if name in services:
            del services[name]

    # Collect names of services we're about to add (skip path adjustment for
    # these — their paths are already relative to the output subdirectory).
    added_service_names: set[str] = set()

    # Add new services
    for svc_yaml in variant.add_services_yaml:
        helper = YAML()
        helper.preserve_quotes = True
        parsed = helper.load(svc_yaml)
        for svc_name, svc_def in parsed.items():
            services[svc_name] = svc_def
            added_service_names.add(svc_name)

    # Apply environment overrides
    for svc_name, overrides in variant.env_overrides.items():
        if svc_name not in services:
            continue
        svc = services[svc_name]
        if not isinstance(svc, CommentedMap):
            continue
        env = svc.get("environment")
        if env is None:
            env = []
            svc["environment"] = env
        if isinstance(env, list):
            # Remove existing entries for overridden keys, then append
            for key in overrides:
                env[:] = [
                    e
                    for e in env
                    if not (isinstance(e, str) and e.startswith(key + "="))
                ]
                env.append(f"{key}={overrides[key]}")

    # Adjust relative paths for services from the base file (not added ones)
    if variant.output_dir:
        for name in services:
            if name in added_service_names:
                continue
            svc = services[name]
            if isinstance(svc, CommentedMap):
                adjust_service_paths(svc)

    # Add volumes
    if variant.add_volumes and "volumes" in data:
        for vol_name in variant.add_volumes:
            data["volumes"][vol_name] = None

    # Serialize
    buf = StringIO()
    yaml_inst.dump(data, buf)
    body = buf.getvalue()

    # Strip commented-out blocks
    body = remove_commented_blocks(body, variant.strip_commented_blocks)

    # Strip the original header comment (everything before "name:")
    idx = body.find("name:")
    if idx > 0:
        body = body[idx:]

    # Ensure blank lines before added services and the top-level volumes section
    for svc_name in added_service_names:
        body = ensure_blank_line_before(body, re.escape(f"  {svc_name}:"))
    body = ensure_blank_line_before(body, r"volumes:\n")

    return variant.header + body


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def output_path(variant: Variant) -> Path:
    return SCRIPT_DIR / variant.output_dir / "docker-compose.yml"


def run_generate(variant: Variant) -> None:
    generated = generate(variant)
    out = output_path(variant)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generated)
    print(f"Generated {out.relative_to(SCRIPT_DIR)}")


def run_check(variant: Variant) -> bool:
    """Return True if up to date."""
    generated = generate(variant)
    out = output_path(variant)

    if not out.exists():
        print(
            f"ERROR: {out.relative_to(SCRIPT_DIR)} does not exist. "
            f"Run without --check to generate it."
        )
        return False

    existing = out.read_text()
    if existing == generated:
        print(f"OK: {out.relative_to(SCRIPT_DIR)} is up to date.")
        return True

    diff = difflib.unified_diff(
        existing.splitlines(keepends=True),
        generated.splitlines(keepends=True),
        fromfile=str(out.relative_to(SCRIPT_DIR)),
        tofile="(generated)",
    )
    sys.stdout.writelines(diff)
    print(
        f"\nERROR: {out.relative_to(SCRIPT_DIR)} is out of date. "
        f"Run 'uv run generate_compose_variants.py {variant.name}' to update."
    )
    return False


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate docker-compose variant files from docker-compose.yml"
    )
    parser.add_argument(
        "variant",
        nargs="?",
        choices=list(VARIANTS.keys()),
        help="Variant to generate (default: all)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check that generated files match existing ones (for CI / pre-commit)",
    )
    args = parser.parse_args()

    targets = [VARIANTS[args.variant]] if args.variant else list(VARIANTS.values())

    if args.check:
        all_ok = all(run_check(v) for v in targets)
        sys.exit(0 if all_ok else 1)
    else:
        for v in targets:
            run_generate(v)


if __name__ == "__main__":
    main()
