# /// script
# requires-python = ">=3.11"
# dependencies = ["ruamel.yaml>=0.18"]
# ///
"""Generate docker-compose variant files from the main docker-compose.yml.

Each variant defines which services to remove, which to add, which
commented-out blocks to strip, and where to write the output. The main
docker-compose.yml is the single source of truth — variants are derived
from it so shared service definitions never drift.

Usage:
    uv run generate_compose_variants.py                   # generate all variants
    uv run generate_compose_variants.py headless           # generate one variant
    uv run generate_compose_variants.py --check            # check all (CI / pre-commit)
    uv run generate_compose_variants.py --check headless   # check one
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from dataclasses import dataclass
from dataclasses import field
from io import StringIO
from pathlib import Path

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap


# ---------------------------------------------------------------------------
# Variant configuration
# ---------------------------------------------------------------------------


@dataclass
class Variant:
    """Describes how to derive a compose file from the main docker-compose.yml."""

    # Variant name (used as CLI argument).
    name: str
    # Subdirectory (relative to SCRIPT_DIR) for the output file.
    output_dir: str
    # Header comment placed at the top of the generated file.
    header: str
    # Service names to remove from the base compose file.
    remove_services: set[str] = field(default_factory=set)
    # YAML strings defining services to add. Each string is a single-service
    # YAML document (e.g. "cli_server:\n  image: ...").
    add_services_yaml: list[str] = field(default_factory=list)
    # Volume names to add to the top-level volumes section.
    add_volumes: list[str] = field(default_factory=list)
    # Commented-out service block names to strip (regex-matched).
    strip_commented_blocks: list[str] = field(default_factory=list)
    # Environment overrides to apply to existing services.
    # Maps service_name -> {env_var: value}. Added/overridden in the
    # service's `environment` list.
    env_overrides: dict[str, dict[str, str]] = field(default_factory=dict)
    # Volume names to remove from the top-level volumes section.
    remove_volumes: set[str] = field(default_factory=set)


VARIANTS: dict[str, Variant] = {}


def register(v: Variant) -> Variant:
    VARIANTS[v.name] = v
    return v


# -- headless ---------------------------------------------------------------

register(
    Variant(
        name="headless",
        output_dir="headless",
        header="""\
# =============================================================================
# ONYX HEADLESS DOCKER COMPOSE (AUTO-GENERATED)
# =============================================================================
# This file is generated by generate_compose_variants.py from docker-compose.yml.
# DO NOT EDIT THIS FILE DIRECTLY — your changes will be overwritten.
#
# To regenerate:
#   cd deployment/docker_compose
#   uv run generate_compose_variants.py headless
#
# Usage:
#   cd deployment/docker_compose/headless
#   docker compose up -d
#
# Connect via SSH:
#   ssh localhost -p 2222
# =============================================================================

""",
        remove_services={"web_server", "nginx"},
        add_services_yaml=[
            """\
cli_server:
  image: ${ONYX_CLI_IMAGE:-onyxdotapp/onyx-cli:${IMAGE_TAG:-latest}}
  command: ["serve", "--host", "0.0.0.0", "--port", "2222"]
  depends_on:
    - api_server
  restart: unless-stopped
  ports:
    - "${ONYX_SSH_PORT:-2222}:2222"
  environment:
    - ONYX_SERVER_URL=http://api_server:8080
  volumes:
    - cli_config:/home/onyx/.config
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "6"
"""
        ],
        add_volumes=["cli_config"],
        strip_commented_blocks=["mcp_server", "certbot"],
    )
)


# -- headless-lite ----------------------------------------------------------

register(
    Variant(
        name="headless-lite",
        output_dir="headless-lite",
        header="""\
# =============================================================================
# ONYX HEADLESS-LITE DOCKER COMPOSE (AUTO-GENERATED)
# =============================================================================
# This file is generated by generate_compose_variants.py from docker-compose.yml.
# DO NOT EDIT THIS FILE DIRECTLY — your changes will be overwritten.
#
# To regenerate:
#   cd deployment/docker_compose
#   uv run generate_compose_variants.py headless-lite
#
# Usage:
#   cd deployment/docker_compose/headless-lite
#   docker compose up -d
#
# Connect via SSH:
#   ssh localhost -p 2222
#
# This is a minimal headless deployment: no web UI, no Vespa, no Redis,
# no model servers, no background workers, no OpenSearch, and no MinIO.
# Only PostgreSQL is required. Connectors and RAG search are disabled,
# but core chat (LLM conversations, tools, user file uploads, Projects,
# Agent knowledge, code interpreter) still works.
# =============================================================================

""",
        remove_services={
            "web_server",
            "nginx",
            "background",
            "cache",
            "index",
            "indexing_model_server",
            "inference_model_server",
            "opensearch",
            "minio",
        },
        add_services_yaml=[
            """\
cli_server:
  image: ${ONYX_CLI_IMAGE:-onyxdotapp/onyx-cli:${IMAGE_TAG:-latest}}
  command: ["serve", "--host", "0.0.0.0", "--port", "2222"]
  depends_on:
    - api_server
  restart: unless-stopped
  ports:
    - "${ONYX_SSH_PORT:-2222}:2222"
  environment:
    - ONYX_SERVER_URL=http://api_server:8080
  volumes:
    - cli_config:/home/onyx/.config
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "6"
"""
        ],
        add_volumes=["cli_config"],
        remove_volumes={
            "vespa_volume",
            "model_cache_huggingface",
            "indexing_huggingface_model_cache",
            "background_logs",
            "inference_model_server_logs",
            "indexing_model_server_logs",
            "opensearch-data",
            "minio_data",
        },
        strip_commented_blocks=["mcp_server", "certbot"],
        env_overrides={
            "api_server": {
                "DISABLE_VECTOR_DB": "true",
                "FILE_STORE_BACKEND": "postgres",
                "CACHE_BACKEND": "postgres",
                "AUTH_BACKEND": "postgres",
            },
        },
    )
)


# ---------------------------------------------------------------------------
# YAML helpers
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent
SOURCE = SCRIPT_DIR / "docker-compose.yml"


def load_yaml() -> tuple[YAML, CommentedMap]:
    yaml = YAML()
    yaml.preserve_quotes = True
    yaml.width = 4096  # avoid line wrapping
    with open(SOURCE) as f:
        data = yaml.load(f)
    return yaml, data


# ---------------------------------------------------------------------------
# Service transforms (for standalone output files)
# ---------------------------------------------------------------------------


def strip_build_blocks(services: CommentedMap) -> None:
    """Remove ``build`` keys from all services.

    Generated files are intended to be downloaded and used standalone — users
    pull pre-built images rather than building from source, so ``build``
    blocks are not useful and contain repo-relative paths that won't exist.
    """
    for svc in services.values():
        if isinstance(svc, CommentedMap) and "build" in svc:
            del svc["build"]


# ---------------------------------------------------------------------------
# Text post-processing
# ---------------------------------------------------------------------------


def remove_commented_blocks(text: str, block_names: list[str]) -> str:
    """Remove commented-out service blocks matching *block_names*."""
    if not block_names:
        return text

    pattern = re.compile(
        r"^\s*#\s*(" + "|".join(re.escape(n) for n in block_names) + r"):"
    )

    lines = text.split("\n")
    result: list[str] = []
    skip = False
    blank_run = 0

    for line in lines:
        if pattern.match(line):
            skip = True
            # Remove preceding comment/blank lines that introduce the block
            while result and (
                result[-1].strip().startswith("#") or result[-1].strip() == ""
            ):
                result.pop()
            continue
        if skip:
            stripped = line.strip()
            if stripped.startswith("#") or stripped == "":
                continue
            else:
                skip = False

        if line.strip() == "":
            blank_run += 1
            if blank_run > 2:
                continue
        else:
            blank_run = 0

        result.append(line)

    return "\n".join(result)


def ensure_blank_line_before(text: str, pattern: str) -> str:
    """Ensure there is a blank line before lines matching *pattern*."""
    return re.sub(r"(\n)(" + pattern + r")", r"\1\n\2", text)


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------


def generate(variant: Variant) -> str:
    """Generate the variant's docker-compose.yml content."""
    yaml_inst, data = load_yaml()

    services = data["services"]

    # Remove services
    for name in variant.remove_services:
        if name in services:
            del services[name]

    # Clean up depends_on entries that reference removed services
    remaining_services = set(services.keys())
    for svc_name in list(services):
        svc = services[svc_name]
        if not isinstance(svc, CommentedMap) or "depends_on" not in svc:
            continue
        deps = svc["depends_on"]
        if isinstance(deps, list):
            deps[:] = [d for d in deps if d in remaining_services]
            if not deps:
                del svc["depends_on"]
        elif isinstance(deps, CommentedMap):
            for dep_name in list(deps):
                if dep_name not in remaining_services:
                    del deps[dep_name]
            if not deps:
                del svc["depends_on"]

    # Collect names of services we're about to add (skip path adjustment for
    # these — their paths are already relative to the output subdirectory).
    added_service_names: set[str] = set()

    # Add new services
    for svc_yaml in variant.add_services_yaml:
        helper = YAML()
        helper.preserve_quotes = True
        parsed = helper.load(svc_yaml)
        for svc_name, svc_def in parsed.items():
            services[svc_name] = svc_def
            added_service_names.add(svc_name)

    # Apply environment overrides
    for svc_name, overrides in variant.env_overrides.items():
        if svc_name not in services:
            continue
        svc = services[svc_name]
        if not isinstance(svc, CommentedMap):
            continue
        env = svc.get("environment")
        if env is None:
            env = []
            svc["environment"] = env
        if isinstance(env, list):
            # Remove existing entries for overridden keys, then append
            for key in overrides:
                env[:] = [
                    e
                    for e in env
                    if not (isinstance(e, str) and e.startswith(key + "="))
                ]
                env.append(f"{key}={overrides[key]}")

    # Strip build blocks — generated files are standalone downloads, users
    # pull images rather than building from source.
    strip_build_blocks(services)

    # Add volumes
    if variant.add_volumes and "volumes" in data:
        for vol_name in variant.add_volumes:
            data["volumes"][vol_name] = None

    # Remove volumes
    if variant.remove_volumes and "volumes" in data:
        for vol_name in variant.remove_volumes:
            if vol_name in data["volumes"]:
                del data["volumes"][vol_name]

    # Serialize
    buf = StringIO()
    yaml_inst.dump(data, buf)
    body = buf.getvalue()

    # Strip commented-out blocks
    body = remove_commented_blocks(body, variant.strip_commented_blocks)

    # Strip the original header comment (everything before "name:")
    idx = body.find("name:")
    if idx > 0:
        body = body[idx:]

    # Ensure blank lines before added services and the top-level volumes section
    for svc_name in added_service_names:
        body = ensure_blank_line_before(body, re.escape(f"  {svc_name}:"))
    body = ensure_blank_line_before(body, r"volumes:\n")

    return variant.header + body


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def output_path(variant: Variant) -> Path:
    return SCRIPT_DIR / variant.output_dir / "docker-compose.yml"


def run_generate(variant: Variant) -> None:
    generated = generate(variant)
    out = output_path(variant)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generated)
    print(f"Generated {out.relative_to(SCRIPT_DIR)}")


def run_check(variant: Variant) -> bool:
    """Return True if up to date."""
    generated = generate(variant)
    out = output_path(variant)

    if not out.exists():
        print(
            f"ERROR: {out.relative_to(SCRIPT_DIR)} does not exist. "
            f"Run without --check to generate it."
        )
        return False

    existing = out.read_text()
    if existing == generated:
        print(f"OK: {out.relative_to(SCRIPT_DIR)} is up to date.")
        return True

    diff = difflib.unified_diff(
        existing.splitlines(keepends=True),
        generated.splitlines(keepends=True),
        fromfile=str(out.relative_to(SCRIPT_DIR)),
        tofile="(generated)",
    )
    sys.stdout.writelines(diff)
    print(
        f"\nERROR: {out.relative_to(SCRIPT_DIR)} is out of date. "
        f"Run 'uv run generate_compose_variants.py {variant.name}' to update."
    )
    return False


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate docker-compose variant files from docker-compose.yml"
    )
    parser.add_argument(
        "variant",
        nargs="?",
        choices=list(VARIANTS.keys()),
        help="Variant to generate (default: all)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check that generated files match existing ones (for CI / pre-commit)",
    )
    args = parser.parse_args()

    targets = [VARIANTS[args.variant]] if args.variant else list(VARIANTS.values())

    if args.check:
        all_ok = all(run_check(v) for v in targets)
        sys.exit(0 if all_ok else 1)
    else:
        for v in targets:
            run_generate(v)


if __name__ == "__main__":
    main()
