// Style Dictionary build script (programmatic API, Style Dictionary v4).
//
// Single token source (tokens/opal/**.json) -> three platform outputs:
//   - web/opal: dist/tokens.css         CSS custom properties, EXACT Opal names,
//               :root (primitives + light semantic) + .dark (dark semantic),
//               references preserved as var(--x) so dark mode flips at runtime.
//   - mobile:   dist/nativewind-theme.cjs  a Tailwind `theme.extend` fragment
//               (semantic colors as var(--name); dimensions resolved to px numbers).
//   - mobile:   dist/native.js + native.d.ts  light/dark CSS-variable maps for the
//               NativeWind vars() provider (the RN analog of web's `.dark` class).
//
// Run via `node style-dictionary.config.mjs` (the `build:tokens` script).
// Style Dictionary is a devDependency and never ships, so it cannot affect a
// consumer's runtime dependency graph.
//
// Token model (see tokens/opal/*.json):
//   - primitives / size / typography: top-level keys, path = [name].
//   - semantic light:  nested under "light", path = ["light", name].
//   - semantic dark:   nested under "dark",  path = ["dark", name].
// The CSS var name is always the LAST path segment, verbatim (no prefix, no
// kebab mangling) — Opal's names like `alpha-grey-100-90` / `neon-amber-a60`
// must survive byte-for-byte, which lodash kebab-case would break.

import StyleDictionary from "style-dictionary";

const leaf = (token) => token.path[token.path.length - 1];
const isColor = (token) => (token.type ?? token.$type) === "color";
const rawOriginal = (token) => token.original.value ?? token.original.$value;
const resolved = (token) => token.value ?? token.$value;

// `{a-b-c}` (or `{group.a-b-c}`) -> `var(--a-b-c)` using the reference's last
// path segment, then collapse internal whitespace (font-family values span lines).
function cssValue(rawValue) {
  return String(rawValue)
    .replace(/\{([^}]+)\}/g, (_, ref) => {
      const segs = ref.split(".");
      return `var(--${segs[segs.length - 1]})`;
    })
    .replace(/\s+/g, " ")
    .trim();
}

// rem/px/unitless string -> Number of px (React Native style objects are unitless px).
function toPx(rawValue) {
  const v = String(rawValue).trim();
  if (v.endsWith("rem")) return parseFloat(v) * 16;
  if (v.endsWith("px")) return parseFloat(v);
  return Number(v);
}

// A CSS font-family stack -> the first family name (React Native takes one family).
function firstFamily(stack) {
  return String(stack)
    .split(",")[0]
    .trim()
    .replace(/^["']|["']$/g, "");
}

// Identity name transform: the CSS var name is the verbatim last path segment.
StyleDictionary.registerTransform({
  name: "name/opal-literal",
  type: "name",
  transform: (token) => leaf(token),
});

// ---- Web/opal CSS: exact names, :root + .dark, references kept as var() ----
StyleDictionary.registerFormat({
  name: "css/opal",
  format: ({ dictionary }) => {
    // Typography presets (path[0] === "text") are emitted as @utility blocks by
    // css/opal-typography, not as flat variables here.
    const rootTokens = dictionary.allTokens.filter(
      (t) => t.path[0] !== "dark" && t.path[0] !== "text"
    );
    const darkTokens = dictionary.allTokens.filter((t) => t.path[0] === "dark");
    const block = (sel, tokens) =>
      `${sel} {\n` +
      tokens
        .map((t) => `  --${leaf(t)}: ${cssValue(rawOriginal(t))};`)
        .join("\n") +
      `\n}\n`;
    return (
      "/* Generated by Style Dictionary. Source of truth: tokens/opal/*.json. */\n" +
      "/* Do not edit by hand. */\n\n" +
      block(":root", rootTokens) +
      "\n" +
      block(".dark", darkTokens)
    );
  },
});

// ---- Web/opal typography: regenerate the `@utility font-*` preset blocks ----
// Each preset (path[0] === "text") becomes a Tailwind v4 @utility, byte-equivalent
// to Opal's hand-authored blocks. Values keep their `var()` refs (font families and
// height metrics) so they still resolve from tokens.css at runtime.
const TYPO_PROP_ORDER = [
  ["fontFamily", "font-family"],
  ["fontSize", "font-size"],
  ["fontWeight", "font-weight"],
  ["lineHeight", "line-height"],
  ["letterSpacing", "letter-spacing"],
];
StyleDictionary.registerFormat({
  name: "css/opal-typography",
  format: ({ dictionary }) => {
    const presets = {};
    const order = [];
    for (const t of dictionary.allTokens) {
      if (t.path[0] !== "text") continue;
      const name = t.path[1];
      if (!presets[name]) {
        presets[name] = {};
        order.push(name);
      }
      presets[name][t.path[2]] = cssValue(rawOriginal(t));
    }
    let out =
      "/* Generated by Style Dictionary. Source of truth: tokens/opal/typography-presets.json. */\n" +
      "/* Do not edit by hand. Typography preset utilities (web/Opal). */\n\n";
    for (const name of order) {
      out += `@utility font-${name} {\n`;
      for (const [key, cssProp] of TYPO_PROP_ORDER) {
        if (presets[name][key] !== undefined) {
          out += `  ${cssProp}: ${presets[name][key]};\n`;
        }
      }
      out += `}\n\n`;
    }
    return out;
  },
});

// ---- Mobile: NativeWind `theme.extend` fragment (CJS, required by tailwind.config) ----
StyleDictionary.registerFormat({
  name: "js/nativewind-theme",
  format: ({ dictionary }) => {
    // Colors: every color token name -> var(--name). Resolved at runtime by the
    // vars() provider (lightVars/darkVars), mirroring web's CSS-variable model.
    // De-dupe by name (a semantic name exists in both light & dark).
    const colorNames = [
      ...new Set(dictionary.allTokens.filter(isColor).map(leaf)),
    ].sort();
    const colors = Object.fromEntries(
      colorNames.map((n) => [n, `var(--${n})`])
    );
    // borderRadius: radius-* tokens -> resolved px numbers (rounded-12 etc.).
    const borderRadius = {};
    for (const t of dictionary.allTokens) {
      const n = leaf(t);
      const m = n.match(/^radius-(.+)$/);
      if (m) borderRadius[m[1] === "round" ? "full" : m[1]] = toPx(resolved(t));
    }
    // spacing: spacing-block-* / spacing-inline-* -> px numbers.
    const spacing = {};
    for (const t of dictionary.allTokens) {
      const n = leaf(t);
      const m = n.match(/^spacing-(?:block|inline)-(.+)$/);
      if (m) spacing[m[1]] = toPx(resolved(t));
    }
    const theme = { colors, borderRadius, spacing };
    return (
      "// Generated by Style Dictionary. Source of truth: tokens/opal/*.json.\n" +
      "// Do not edit by hand. NativeWind `theme.extend` fragment for mobile.\n" +
      "module.exports = " +
      JSON.stringify(theme, null, 2) +
      ";\n"
    );
  },
});

// ---- Mobile: type declarations for native.js ----
StyleDictionary.registerFormat({
  name: "dts/native-vars",
  format: () =>
    "// Generated by Style Dictionary. Do not edit by hand.\n" +
    "export declare const varsLight: Record<string, string>;\n" +
    "export declare const varsDark: Record<string, string>;\n" +
    "export interface TextPreset {\n" +
    "  fontFamily: string;\n" +
    "  fontSize: number;\n" +
    "  fontWeight: string;\n" +
    "  lineHeight: number;\n" +
    "  letterSpacing: number;\n" +
    "}\n" +
    "export declare const textPresets: Record<string, TextPreset>;\n",
});

// ---- Mobile: light/dark CSS-variable maps for the vars() provider (ESM) ----
StyleDictionary.registerFormat({
  name: "js/native-vars",
  format: ({ dictionary }) => {
    const colors = dictionary.allTokens.filter(isColor);
    const build = (excludeMode) => {
      const out = {};
      for (const t of colors) {
        if (t.path[0] === excludeMode) continue; // drop the other mode's overrides
        out[`--${leaf(t)}`] = String(resolved(t)); // resolved hex (primitive value)
      }
      return out;
    };
    const varsLight = build("dark"); // primitives + light semantic
    const varsDark = build("light"); // primitives + dark semantic
    // Typography presets as RN-ready style objects (resolved numbers + single family).
    const textPresets = {};
    for (const t of dictionary.allTokens) {
      if (t.path[0] !== "text") continue;
      const name = t.path[1];
      const prop = t.path[2];
      const preset = (textPresets[name] ??= {});
      const val = resolved(t);
      if (prop === "fontFamily") preset.fontFamily = firstFamily(val);
      else if (prop === "fontWeight") preset.fontWeight = String(val);
      else preset[prop] = toPx(val); // fontSize / lineHeight / letterSpacing
    }
    return (
      "// Generated by Style Dictionary. Source of truth: tokens/opal/*.json.\n" +
      "// Do not edit by hand. Light/dark variable maps + text presets for mobile.\n" +
      "export const varsLight = " +
      JSON.stringify(varsLight, null, 2) +
      ";\n\nexport const varsDark = " +
      JSON.stringify(varsDark, null, 2) +
      ";\n\nexport const textPresets = " +
      JSON.stringify(textPresets, null, 2) +
      ";\n"
    );
  },
});

const sd = new StyleDictionary({
  source: ["tokens/opal/**/*.json"],
  log: { verbosity: "default", warnings: "warn" },
  platforms: {
    out: {
      // Only a name transform — value transforms are intentionally omitted so
      // token.value stays the exact authored literal (no hex/unit rewriting),
      // while token.original.value preserves the `{ref}` form for the CSS output.
      transforms: ["name/opal-literal"],
      buildPath: "dist/",
      files: [
        { destination: "tokens.css", format: "css/opal" },
        { destination: "typography.css", format: "css/opal-typography" },
        { destination: "nativewind-theme.cjs", format: "js/nativewind-theme" },
        { destination: "native.js", format: "js/native-vars" },
        { destination: "native.d.ts", format: "dts/native-vars" },
      ],
    },
  },
});

await sd.buildAllPlatforms();
