{{- if and (.Values.api.autoscaling.enabled) (ne (include "onyx-stack.autoscaling.engine" .) "keda") }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "onyx.fullname" . }}-api
  labels:
    {{- include "onyx.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
<<<<<<< HEAD:deployment/helm/charts/onyx/templates_disabled/api-hpa.yaml
    name: {{ include "onyx.fullname" . }}
=======
    name: {{ include "onyx-stack.fullname" . }}-api-server
>>>>>>> 59a5dc26a (feat(infra): Defaul to HPA w/ KEDA option):deployment/helm/charts/onyx/templates/api-hpa.yaml
  minReplicas: {{ .Values.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.api.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.api.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.api.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.api.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
