{{- if .Values.monitoring.serviceMonitors.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "onyx.fullname" . }}-api
  labels:
    {{- include "onyx.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitors.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Values.api.deploymentLabels.app }}
  endpoints:
    - port: api-server-port
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      {{- if and .Values.auth.metricsToken (ne (toString .Values.auth.metricsToken.enabled) "false") }}
      authorization:
        type: Bearer
        credentials:
          name: {{ include "onyx.secretName" .Values.auth.metricsToken }}
          key: {{ default "metrics_auth_token" .Values.auth.metricsToken.secretKeys.METRICS_AUTH_TOKEN }}
      {{- end }}
{{- end }}
