{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "onyx-stack.fullname" . }}-ingress-webserver
  annotations:
    {{- if .Values.letsencrypt.enabled -}}
    cert-manager.io/cluster-issuer: {{ include "onyx-stack.fullname" . }}-letsencrypt
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- with .Values.ingress.webserver.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.webserver.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "onyx-stack.fullname" . }}-webserver
                port:
                  number: {{ .Values.webserver.service.servicePort }}
  tls:
    - hosts:
        - {{ .Values.ingress.webserver.host }}
      secretName: {{ .Values.ingress.webserver.tlsSecretName | default (printf "%s-ingress-webserver-tls" (include "onyx-stack.fullname" .)) }}
{{- end }}
