{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "onyx-stack.fullname" . }}-ingress-api
  annotations:
    {{- if .Values.letsencrypt.enabled -}}
    cert-manager.io/cluster-issuer: {{ include "onyx-stack.fullname" . }}-letsencrypt
    {{- end }}
    {{- with .Values.ingress.api.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.api.host }}
      http:
        paths:
          - path: {{ .Values.ingress.api.path }}
            pathType: {{ .Values.ingress.api.pathType }}
            backend:
              service:
                name: {{ include "onyx-stack.fullname" . }}-api-service
                port:
                  number: {{ .Values.api.service.servicePort }}
  tls:
    - hosts:
        - {{ .Values.ingress.api.host }}
      secretName: {{ .Values.ingress.api.tlsSecretName | default (printf "%s-ingress-api-tls" (include "onyx-stack.fullname" .)) }}
{{- end }}
