name: Render PR Preview
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Reusable workflow published by Render
      - uses: render-examples/preview-environment-action@v1
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}