name: Render Preview Environment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    name: Deploy Preview Environment
    uses: render-examples/preview-environment/.github/workflows/preview-environment.yml@v1
    with:
      api-key: ${{ secrets.RENDER_API_KEY }}